### ISSUE TITLE
authenticate() best practices

### ISSUE THREAD

**Issue by aldoforce** [omniphx/forrest#100]
In order to execute a query or any operation you previously had to execute the authenticate() method.
Where this authentication is stored? I don't want to authenticate every time so I was thinking of saving a Singleton instance of Forrest and re-use it as required.

Is there any "best practice" on how to implement this?

I'm using User-Password flow.

Thanks for this great plugin.

Regards,
--Aldo

**Comment by omniphx** [comment]
Hi @aldoforce, this package stores an authentication token through the session or cache depending on how you configure it.

So definitely no need to authenticate for each request!

-Matt
