### ISSUE TITLE
Call to undefined method Omniphx\Forrest\Providers\Laravel\ForrestServiceProvider::query()

### ISSUE THREAD

**Issue by kaypro4** [omniphx/forrest#102]
Hello, apologies for the newbie problem but I've spent quite a bit of time retracing the setup process and am still getting this error.

I get this when I call `Forrest::query('SELECT Id, Name FROM Account')` from within a controller.  I have this at the top of the controller:

`use Omniphx\Forrest\Providers\Laravel\ForrestServiceProvider as Forrest;`

The query call succeeds when I put it within a route directly and then pass the results to the view using `View::make`.

I'm on Laravel 5.2 and Forrest 2.1.3. 

I've triple checked the app.php config and all looks good there. And figure it must be right if the statement works in the route directly.

Any help is much appreciated!

Thanks

**Comment by omniphx** [comment]
Hey @kaypro4,

Assuming the app.php is set up correctly, all you need to do is add `use Forrest;` and it should work!

Cheers!

**Comment by kaypro4** [comment]
@omniphx well that's embarrassing... Working perfectly now with just `use Forrest;`. 

Thanks for the quick help, and thanks for the great package!
