### ISSUE TITLE
Undefined index: query error in Client.php line 342

### ISSUE THREAD

**Issue by hasib32** [omniphx/forrest#103]
We are using your package. It's been working fine. But from today we are getting the above error. I checked the salesforce response. It's giving us this repose: TLS 1.0 has been disabled in this organization. Please use TLS 1.1 or higher when connecting to Salesforce using https. I think now slaesfore require to use TLS1.1 for connection. You can look this page: https://help.salesforce.com/apex/HTViewSolution?id=000221207. Is there anything we need to do or you have to fix the issue?

**Comment by tabirkeland** [comment]
@hasib32 update your SSL cert?
