### ISSUE TITLE
Undefined index sobjects

### ISSUE THREAD

**Issue by pravindahal** [omniphx/forrest#104]
I have a long-running PHP process with the following storage configuration:

```
...
...
...
    'storage'        => [
        'type'      => 'session', // 'session' or 'cache' are the two options
        'path'      => 'forrest_', // unique storage path to avoid collisions
        'expire_in' => 10080, // number of minutes to expire cache/session
    ],
...
...
...
```

It works fine for a few hours... but then after a few hours, I get Undefined index sobjects. The error occurs in Client.php (586):

```
...
...
...
    public function __call($name, $arguments)
    {
        $url = $this->getInstanceUrl();
        $url .= $this->storage->get('resources')[$name]; // <- error on this line

        $options = [];
...
...
...
```

Will post trace later.

It's probably because of how laravel handles session expiry. Graceful handling of this would be helpful.

**Comment by joaopaulonobrega** [comment]
hi @pravindahal , 
I think @tabirkeland solution will serve for you 

See [issue #97](https://github.com/omniphx/forrest/issues/97)
