### ISSUE TITLE
forrest.php is not generated when executing php artisan vendor:publish

### ISSUE THREAD

**Issue by bunlongheng** [omniphx/forrest#108]
I added `"omniphx/forrest": "2.0.*@dev"` in composer.json.
I adde services provider and alias. Then, I ran `php artisan vendor:publish`

On CLI, I got `Publishing complete for tag []!`

I noticed **forrest.php** is not generated. 

Did I do anything wrong ? Is it an intended behavior ? Please kindly advise.

**Comment by joaopaulonobrega** [comment]
@bunlongheng  you put the facede and provider?

**Provider**
Omniphx\Forrest\Providers\Laravel\ForrestServiceProvider::class

**Facade**
'Forrest' => Omniphx\Forrest\Providers\Laravel\Facades\Forrest::class

**Comment by omniphx** [comment]
@bunlongheng, can you try changing your version to `"omniphx/forrest": "2.*"`?
