### ISSUE TITLE
What is 'loginURL' for Salesforce ?

### ISSUE THREAD

**Issue by bunlongheng** [omniphx/forrest#109]
You said, 

After saving, you will now be given a Consumer Key and Consumer Secret. Update your config file with values for consumerKey, consumerSecret, loginURL and callbackURI.

I only see 3 : consumerKey, consumerSecret, and callbackURI.
I don't see **loginURL**. 

With that said, what should I put in my credentials settings for login url : 

```
'credentials'    => [
       
        'consumerKey'    => env('SALESFORCE_CONSUMER_KEY'),
        'consumerSecret' => env('SALESFORCE_CONSUMER_SECRET'),
        'callbackURI'    => env('SALESFORCE_CALLBACK_URI'),
        'loginURL'       => env('SALESFORCE_LOGIN_URL'),  // <----- ????
        
    ],
```

Is it https://login.salesforce.com/ ?

**Comment by joaopaulonobrega** [comment]
Hi @bunlongheng , loginURL is the url that salesforce provides for your company access. e.g
https://{yourcompanyname}.salesforce.com

**Comment by omniphx** [comment]
@bunlongheng, this will set a default login url if you don't plan on passing the login url into the authentication method. If you are authenticating a developer or production environment, the url will be https://login.salesforce.com as you said.

Hope that helps!
