### ISSUE TITLE
How do I implement "logout"

### ISSUE THREAD

**Issue by FairTradeCertified** [omniphx/forrest#112]
Hi There
In my logout function

Route::get('/logout', function () {
Forrest::revoke();
Session::flush();
return return Redirect::to('/');
})
It doesn't work. no matter this inside or outside the group middleware.

or Are there ways I can make forrest_token to ''  so that it can not login salesforce when logout is click?

Thanks!

**Comment by omniphx** [comment]
Hi @FairTradeCertified, can you elaborate a little more on why "it doesn't work"?

**Comment by FairTradeCertified** [comment]
Hi omiphx, 

Here is my routes.php

Route::group(['middleware' => 'auth.salesforce'], function () {

    Route::get('/', function () {
        return Redirect::to('/abc');
    });

    Route::get('/abc', 'TransactionsController@viewReports');

    Route::get('/logout', function () {

        Forrest::revoke();
        Session::flush();
        return Redirect::to('/');
    });
});

See when /logout is click, It need to logout from Salesforce(SF) or makes token invalid then SF would shows login page. It works fine when a user doesn't login. but, if she/he login, then it can not logout any more.

Thanks!

**Comment by omniphx** [comment]
Are you using cache instead of session for storing your authentication tokens? If so, you need to use `Cache::flush` instead of `Session::flush`

**Comment by FairTradeCertified** [comment]
The middleware is

<?php

namespace App\Http\Middleware;

use Closure;
use Session;

class SalesforceAuthenticate
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if (!$request->session()->has('forrest_token')) {
            return redirect('/authenticate');
        }

        return $next($request);
    }
}

and the /Autheticate is
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Support\Facades\Auth;

class Authenticate
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @param  string|null  $guard
     * @return mixed
     */
    public function handle($request, Closure $next, $guard = null)
    {
        if (Auth::guard($guard)->guest()) {
            if ($request->ajax() || $request->wantsJson()) {
                return response('Unauthorized.', 401);
            } else {
                return redirect()->guest('login');
            }
        }

        return $next($request);
    }
}

Thanks!

**Comment by FairTradeCertified** [comment]
Actually, after Session::fluch; I dd(Session::all()), it gets array() nothing, but after it redirects. it login again without signed information. So it looks like to have nothing to do with session in the client application. I am trying to use "Cache::flush(); " now.

Thanks!

**Comment by FairTradeCertified** [comment]
Cache::flush();  it doesn't work for this case.

**Comment by omniphx** [comment]
It sounds like what you're saying is that you are logging out and when you try logging back in, it will automatically reauthorize the app without entering any credentials despite there being nothing stored in the session.

One possible reason for causing this is if you have a Salesforce session running in another tab or have recently logged into Salesforce without logging out.

Can you try this:
# Log out of your laravel app
# Clear your browser cookies
# Try logging back in

If this works, Salesforce is reauthorizing you because you already have an existing session. Granted this is pretty frustrating if you intended to switch orgs but I don't know if there is anyway I can provide a work-around with this package

**Comment by FairTradeCertified** [comment]
Hi Omniphx,

Sorry for the late response. Right now we can not figure out how to logout through forrest, but we just redirect to 'sandboxurl/'/secur/logout.jsp' to logout. 

Thanks!
