### ISSUE TITLE
JSON Parse Error When Updating a Record

### ISSUE THREAD

**Issue by jkelp** [omniphx/forrest#113]
When successfully updating a Record (using format = JSON), Salesforce returns a response code of 200 and no response body ([Salesforce REST API Docs](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_update_fields.htm)).

It seems that Guzzle (5.3) is trying to `json_encode` the empty response.

I get the following error:
`ParseException in Response.php line 148: Unable to parse JSON data: JSON_ERROR_SYNTAX - Syntax error, malformed JSON`

Is there a way to continue to make the request using JSON and but avoid the ParseException?

Thanks for your help.

**Comment by omniphx** [comment]
Hi @jkelp, I know this is an old issue but I wasn't able to reproduce it. Please let me know if it is still happening!
