### ISSUE TITLE
Ability to configure "exceptions" request option

### ISSUE THREAD

**Issue by jkelp** [omniphx/forrest#114]
Currently, if I request a Record that doesn't exist in Salesforce, a 404 response code is returned. By default, Guzzle (5.3) throws an exception for 4xx and 5xx level responses. 

In Guzzle, if the `exception` request option is set to false, the exception is not thrown.

[Guzzle HTTP Errors](http://docs.guzzlephp.org/en/5.3/clients.html#http-errors)

Can you add a configuration option to allow us to set this option?

I think this could be accomplished by adding the following to the `requestResource()` function in Client.php:

`
if (isset($options['exceptions'])) {
            $parameters['exceptions'] = $options['exceptions'];
}
`

Thanks you.

**Comment by omniphx** [comment]
I like this idea! Should be a simple fix.

Usually Guzzle 6 now, so the configuration can be referenced here: http://docs.guzzlephp.org/en/stable/request-options.html
