### ISSUE TITLE
Manually setting tokens

### ISSUE THREAD

**Issue by dtisgodsson** [omniphx/forrest#120]
Hi there,

If I had Salesforce Token information saved in a database from a User "connecting" their account, is there anyway for me to instantiate Forrest using the previously obtained token?

Any help would be much appreciated.

Cheers,
Darren

**Comment by omniphx** [comment]
Hi @dtisgodsson,

You could create your own storage class that implements `Omniphx\Forrest\Interfaces\StorageInterface`. If the token was valid and the request sent from the same source that sent the token, it should work.

Hope that helps!
Matt

**Comment by dtisgodsson** [comment]
Hi @omniphx, many thanks for replying.

Inside the `Omniphx\Forrest\Providers\Laravel\LaravelStorageProvider` class, there are methods `putTokenData()` and `putRefreshToken()` - I think these might do the trick.

Basically, when a User authenticates Salesforce within my app, I want to store the Auth tokens in the database.

At some point in the future, I want to then call the API on behalf of that User, using the tokens I have in the database. I was hoping to use a method like `putTokenData()` to do this but can't see a way to call methods on the storage class via the `Client`.

Is this currently possible?

**Comment by omniphx** [comment]
Hey @dtisgodsson, yup that would work! I would recommend creating your own ServiceProvider and then passing your custom implementation of the storage class so that `composer update` wouldn't wipe out your changes

**Comment by francoismart** [comment]
hello @omniphx  would you mind elaborate if (and how ...) we could create our own ServiceProvider and connection to forrest settings by adding another keyword like 'database' or 'custom' keyword for reference :

 'storage'        => [
        'type'          => 'session', // 'session' or 'cache' are the two options
