### ISSUE TITLE
Pass state parameter and retrieve on callback

### ISSUE THREAD

**Issue by kaypro4** [omniphx/forrest#121]
Hello, this library is working great and has been a huge time saver for us. Thanks! 

I've found that I'd like to authenticate users that initially hit the site via a 2nd level link (e.g https://mysite.com/thispage) and then return them to that deep link on the site after the callback. It seems that the "state" parameter is designed for this use in the webserver flow so just trying to figure out how to use it.

https://developer.salesforce.com/page/Digging_Deeper_into_OAuth_2.0_on_Force.com

Is there a way to pass this parameter in the authenticate method? It appears as though it is settable at least in the config file:

https://github.com/omniphx/forrest/blob/master/src/config/config.php#L39

But it doesn't look like that parameter is being passed into or accessed within the function:

https://github.com/omniphx/forrest/blob/master/src/Omniphx/Forrest/Authentications/WebServer.php#L46

Thanks
Matt

**Comment by omniphx** [comment]
Closing this ticket since this issue has been resolved in #125
