### ISSUE TITLE
Authenticating Multiple Users

### ISSUE THREAD

**Issue by robbiemoore** [omniphx/forrest#123]
Hi! Firstly, love the library - great job.

This is a question of best practise really - as I'm sure it's something most people require. The username and password are set in the config file - which is static. With multiple users there will be multiple usernames and passwords to authenticate - how should these usernames/passwords be passed to the Forrest::authenticate(); facade method? 

Robbie

**Comment by omniphx** [comment]
Hi @robbiemoore, this library has 2 methods for authenticating: UserPassword (1 user) or WebServer(multiple users)

WebServer is basically OAuth2, so your users can authenticate themselves and make requests with a stored authentication token while making calls from your web app.

Hope that helps!

**Comment by robbiemoore** [comment]
Gotcha, thanks for the help!
