### ISSUE TITLE
UserAuthentication is broken with the new v2.3.1 release

### ISSUE THREAD

**Issue by pravindahal** [omniphx/forrest#129]
I am using this with Laravel 5.1.45.

User Authentication worked fine with v2.3.0 and it is broken in v2.3.1.

To reproduce, simply run:

    Forrest::authenticate();

using UserPassword authentication.

**Comment by pravindahal** [comment]
Stack trace:
> MissingKeyException in LaravelSession.php line 44:
> No value for requested key: resources
> in LaravelSession.php line 44
> at LaravelSession->get('resources') in Client.php line 690
> at Client->__call('determineIfConfigVersionExists', array('20.0', '36.0')) in Client.php line 796
> at Client->storeConfiguredVersion(array(array('label' => 'Winter '11', 'url' => '/services/data/v20.0', 'version' => '20.0'), array('label' => 'Spring '11', 'url' => '/services/data/v21.0', 'version' => '21.0'), array('label' => 'Summer '11', 'url' => '/services/data/v22.0', 'version' => '22.0'), array('label' => 'Winter '12', 'url' => '/services/data/v23.0', 'version' => '23.0'), array('label' => 'Spring '12', 'url' => '/services/data/v24.0', 'version' => '24.0'), array('label' => 'Summer '12', 'url' => '/services/data/v25.0', 'version' => '25.0'), array('label' => 'Winter '13', 'url' => '/services/data/v26.0', 'version' => '26.0'), array('label' => 'Spring '13', 'url' => '/services/data/v27.0', 'version' => '27.0'), array('label' => 'Summer '13', 'url' => '/services/data/v28.0', 'version' => '28.0'), array('label' => 'Winter '14', 'url' => '/services/data/v29.0', 'version' => '29.0'), array('label' => 'Spring '14', 'url' => '/services/data/v30.0', 'version' => '30.0'), array('label' => 'Summer '14', 'url' => '/services/data/v31.0', 'version' => '31.0'), array('label' => 'Winter '15', 'url' => '/services/data/v32.0', 'version' => '32.0'), array('label' => 'Spring '15', 'url' => '/services/data/v33.0', 'version' => '33.0'), array('label' => 'Summer '15', 'url' => '/services/data/v34.0', 'version' => '34.0'), array('label' => 'Winter '16', 'url' => '/services/data/v35.0', 'version' => '35.0'), array('label' => 'Spring '16', 'url' => '/services/data/v36.0', 'version' => '36.0'), array('label' => 'Summer '16', 'url' => '/services/data/v37.0', 'version' => '37.0'), array('label' => 'Winter '17', 'url' => '/services/data/v38.0', 'version' => '38.0'))) in Client.php line 784
> at Client->storeVersion() in Client.php line 823
> at Client->storeResources() in UserPassword.php line 48
> at UserPassword->authenticate() in Facade.php line 213
> at Facade::__callStatic('authenticate', array()) in routes.php line 15
> at RouteServiceProvider->{closure}()
> at call_user_func_array(object(Closure), array()) in Route.php line 155
> at Route->runCallable(object(Request)) in Route.php line 130
> at Route->run(object(Request)) in Router.php line 708
> at Router->Illuminate\Routing\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
> at Pipeline->then(object(Closure)) in Router.php line 710
> at Router->runRouteWithinStack(object(Route), object(Request)) in Router.php line 673
> at Router->dispatchToRoute(object(Request)) in Router.php line 635
> at Router->dispatch(object(Request)) in Kernel.php line 236
> at Kernel->Illuminate\Foundation\Http\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 139
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in VerifyCsrfToken.php line 50
> at VerifyCsrfToken->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(VerifyCsrfToken), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in ShareErrorsFromSession.php line 49
> at ShareErrorsFromSession->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(ShareErrorsFromSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in StartSession.php line 62
> at StartSession->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(StartSession), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in AddQueuedCookiesToResponse.php line 37
> at AddQueuedCookiesToResponse->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(AddQueuedCookiesToResponse), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in EncryptCookies.php line 59
> at EncryptCookies->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(EncryptCookies), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request)) in CheckForMaintenanceMode.php line 44
> at CheckForMaintenanceMode->handle(object(Request), object(Closure))
> at call_user_func_array(array(object(CheckForMaintenanceMode), 'handle'), array(object(Request), object(Closure))) in Pipeline.php line 124
> at Pipeline->Illuminate\Pipeline\{closure}(object(Request))
> at call_user_func(object(Closure), object(Request)) in Pipeline.php line 102
> at Pipeline->then(object(Closure)) in Kernel.php line 122
> at Kernel->sendRequestThroughRouter(object(Request)) in Kernel.php line 87
> at Kernel->handle(object(Request)) in index.php line 53

**Comment by omniphx** [comment]
Thanks for reporting @pravindahal I just merged your PR and created Version 2.3.2

**Comment by pravindahal** [comment]
Awesome! Thanks for quick response.

**Comment by pravindahal** [comment]
Wait, this issue is different and not related to the previous PR:

Looks like the issue is in Client.php function storeResources:

    protected function storeResources()
    {
        try {
            $this->storage->get('version');
        } catch (\Exception $e) {
            $this->storeVersion();
        }

        $resources = $this->resources(['format' => 'json']);
        $this->storage->put('resources', $resources);
    }

It doesn't get version, goes into the Exception path and calls storeVersion(). Then storeVersion tries to storage->get('resources') before having put it somewhere down the call chain to causing deadlock situation.

**Comment by omniphx** [comment]
Oh gotcha! Looks like this is because you are using Laravel 5.1.45. The session driver changed in Laravel 5.2.4.

**Comment by omniphx** [comment]
You have 2 options:1 - switch to the cache storage or build your own ServiceProvider (basically the same one used in Forrest v2.3.0

**Comment by pravindahal** [comment]
I was able to reproduce the issue even when using `cache` storage driver too.

Same MissingKeyException but from Omniphx/Forrest/Providers/Laravel/LaravelCache.php:59

**Comment by omniphx** [comment]
I'll have to build a project with Laravel 5.1 and test this out. I recall having a similar issue when I upgraded to 5.2.4. Sorry for the inconvenience.

**Comment by pravindahal** [comment]
Actually, it was caused by this:
https://github.com/omniphx/forrest/pull/130#event-951068016

Since it was trying to call the function name wrongly, it would go to __call instead and then try to call out to Salesforce... only to find out the 'resources' wasn't set.

**Comment by omniphx** [comment]
Oh that makes sense! Surprised my tests didn't catch that bug. I plan to make some lightweight integration tests soon to test UserPassword authentication. Hopefully, it will be easier to get past these bugs in the future

**Comment by pravindahal** [comment]
Actually, the tests in my code caught them. :)
