### ISSUE TITLE
Lumen Directions Not Complete?

### ISSUE THREAD

**Issue by cwhittl** [omniphx/forrest#132]
If I follow the directions for Lumen it doesn't alias Forrest so I added 

class_alias('Omniphx\Forrest\Providers\Laravel\Facades\Forrest', 'Forrest');

If I do that now I get the error

> FatalThrowableError in LaravelRedirect.php line 19: Class 'Redirect' not found

This is due to Redirect not being a class in Lumen.

Am I missing something?

Also when I run "php artisan vendor:publish" it errors with 

>   There are no commands defined in the "vendor" namespace.

My guess is that it's because that's not Lumen but Laravel.

Thanks!

**Comment by cwhittl** [comment]
I've made some changes, what do you think?
https://github.com/omniphx/forrest/pull/133

**Comment by omniphx** [comment]
Hey @cwhittl, added a few changes to your PR that I think will fix some of the issues you mentioned. I'll try to spin up a Lumen install soon and test it out. Thanks for contributing!
