### ISSUE TITLE
cURL error 3: <url> malformed

### ISSUE THREAD

**Issue by LastxTemplar** [omniphx/forrest#144]
I am getting this error when running `Forrest::authenticate()`:
`cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) `

Not sure where to start debugging this.

**Comment by LastxTemplar** [comment]
Forgot to add the loginUrl, works now.

**Comment by lakshmanbodduluru** [comment]
I am getting same error.
What we need to give in loginUrl..?

Thanks.
