### ISSUE TITLE
invalid_grant error

### ISSUE THREAD

**Issue by LastxTemplar** [omniphx/forrest#146]
I keep getting this error
```
Client error: `POST https://test.salesforce.com/services/oauth2/token` resulted in a `400 Bad Request` response:
{"error":"invalid_grant","error_description":"authentication failure"}
```

I am using the UserPassword flow, I have all my keys and credentials written correctly. I have the IPs Relaxed in my app, I even tried adding the security Token at the end of my password, and I am still getting this error, I'm really stumped at this point and don't know what to do.

Doing a CURL request from my console with the same credentials does work and I can receive a token. I thought maybe a workaround would be to manually do a CURL call and store the token in the session by myself? I just don't know what's the name of the token or how to save it so the library will notice it.

Thanks!

**Comment by LunarDevelopment** [comment]
:+1: I'm getting the same issue with the code in an artisan command where as it works through browser. 

I'm also using UserPassword and the application used to work fine with no known changes to my code base.

**Comment by LastxTemplar** [comment]
I actually switched to not using this library, I am just making curl calls in my controller and it works like a charm.

**Comment by dinnouti** [comment]
@LastxTemplar , can you please provide a code example of the curl calls, if possible also include a SOQL call example.

**Comment by LastxTemplar** [comment]
Sure.
```
$result = shell_exec('curl -v https://test.salesforce.com/services/oauth2/token -d "grant_type=password" -d "client_id=yourclientidhere" -d "client_secret=yourclientsecrethere" -d "username=yourusernamehere" -d "password=yourpasswordhere" 2>/path/to/logs/curl_logs.log');

$obj 		= json_decode($result);
$sf_token 	= $obj->access_token;
```

You now have your token in the `$sf_token` variable.
of course you need to change the `https://test.salesforce.com/services/oauth2/token` to `https://login.salesforce.com/services/oauth2/token` if you are not using the test environment.

Next you can do the necessary calls using that token:
```
shell_exec('curl -v https://aa22.salesforce.com/services/data/v39.0/query/?q=SELECT+name,some_kind_of_id__c+FROM+Custom_Record__c -H "Authorization: Bearer '.$sf_token.'"');
```
`aa22` there is just an example, you can get your correct prefix after you have logged into salesforce through your browser and look at the url.
In case you want to use a different version, you can change the `v39.0` value up there, refer to the docs which version you need, but at this point, 39.0 is the latest.
From what I understand, the SOQL queries are as the same as SQL queries but with `+` signs instead of spaces.

I am getting to know Salesforce myself right now, so I am probably not the best person to ask about more complicated stuff than this. The only other things I managed to get working are Bulk Inserts and Single Upserts.

Hope that helps :)

**Comment by dinnouti** [comment]
Hi @LastxTemplar,  thanks a ton for the example, I tweaked your code to use PHP's curl library. I am leaving in here just  to document

```
$sf_config = array(
	client_id     => '',
	client_secret => '',
	username      => '',
	password      => '', // no need to add password token
	url           => 'https://login.salesforce.com/services/oauth2/token',
	grant_type    => 'password',
	query_srv_url => '/services/data/v20.0/query/'
);

$soql_query = 'SELECT id, name from Account';

// ---------
// first act - get token from salesforce

$curl_post_param  = 'grant_type='. $sf_config[grant_type];
$curl_post_param .= '&client_id='. $sf_config[client_id];
$curl_post_param .= '&client_secret='. $sf_config[client_secret];
$curl_post_param .= '&username='. $sf_config[username];
$curl_post_param .= '&password='. $sf_config[password];

$curl_getToken = curl_init();

curl_setopt_array($curl_getToken, array(
	CURLOPT_URL            => $sf_config[url],
	CURLOPT_RETURNTRANSFER => true,
	CURLOPT_ENCODING       => "",
	CURLOPT_MAXREDIRS      => 10,
	CURLOPT_TIMEOUT        => 30,
	CURLOPT_SSL_VERIFYPEER => false,
	CURLOPT_HTTP_VERSION   => CURL_HTTP_VERSION_1_1,
	CURLOPT_CUSTOMREQUEST  => "POST",
	CURLOPT_POSTFIELDS     => $curl_post_param,
	CURLOPT_HTTPHEADER     => array("content-type: application/x-www-form-urlencoded"),
));

$response = curl_exec($curl_getToken);
$err      = curl_error($curl_getToken);

curl_close($curl_getToken);

if ($err)
{
	echo "cURL Error #:" . $err;
	die();
};

$sf_token = json_decode($response, true);

echo "Salesforce token: \n";
var_dump($sf_token);

// ----------
// Second act - send a soql query to salesforce

$curl_url = $sf_token[instance_url] . $sf_config[query_srv_url] . '?q=' .urlencode($soql_query);

$curl_getSoql = curl_init();
curl_setopt_array($curl_getSoql, array(
	CURLOPT_URL            => $curl_url,
	CURLOPT_RETURNTRANSFER => true,
	CURLOPT_ENCODING       => "",
	CURLOPT_MAXREDIRS      => 10,
	CURLOPT_TIMEOUT        => 30,
	CURLOPT_SSL_VERIFYPEER => false,
	CURLOPT_HTTP_VERSION   => CURL_HTTP_VERSION_1_1,
	CURLOPT_CUSTOMREQUEST  => "GET",
	CURLOPT_HTTPHEADER     => array('Authorization: '. $sf_token[token_type] .' '. $sf_token[access_token]),
));

$response = curl_exec($curl_getSoql);
$err      = curl_error($curl_getSoql);

curl_close($curl_getSoql);

if ($err)
{
	echo "cURL Error #:" . $err;
	die();
};

$sf_soql_reply = json_decode($response, true);
echo "Salesforce SOQL reply: \n";
var_dump($sf_soql_reply);
```

**Comment by redsoxfan2499** [comment]
I also getting the same error. 
`Client error: `POST https://test.salesforce.com/services/oauth2/token` resulted in a `400 Bad Request` response:
{"error":"invalid_grant","error_description":"authentication failure"}`

The weird thing is on my local it works fine. But push to my server getting the same error. I created a test Guzzle function making an API call to a test API and that worked fine. So making API calls from my dev server works. So I took some of the above suggestions and altered the package a bit on my dev site and it works without any errors. I created my own function within Forrest. UserPassword.php file. So, besides this one custom function to authenticate, I am still using the rest of the Forrest package. 
FYI: I went ahead and tried to pass my ENV values and pass them into the $URL but for whatever reason, I would get the same error. I even dumped out the URL and all the values were there but still got the same 400 Bad Request error invalid_grant authentication failure. So I went ahead and hardcoded them in the $result line and it works every time. 

`public function getmytoken()
    {
        $result = shell_exec('curl -v https://login.salesforce.com/services/oauth2/token -d "grant_type=password" -d "client_id=CONSUMER_KEY" -d "client_secret=CONSUMER_SECRET" -d "username=USERNAME" -d "password=PASSWORD"');
       
        $obj = json_decode($result);
        $array = (array) $obj;
       
        $this->tokenRepo->put($array);

        $this->storeVersion();
        $this->storeResources();
    }`

In my web routes file: 
`Route::get('/getmytoken', function(){
    Forrest::getmytoken();
    return Redirect::to('/');
});`

Thanks for making this package. Not sure what the exact problem is causing our issues, but it seems  besides the authenticate function, the package works great.

**Comment by comanche** [comment]
I was having similar issues on Windows.  Upon further inspection, I saw that the credentials passed to the request was not what I put in the `.env` file.

```php
// vendor/omniphx/forrest/src/Omniphx/Forrest/Providers/BaseServiceProvider.php

abstract class BaseServiceProvider extends ServiceProvider
{
    // ...

    public function register()
    {
        $this->app->singleton('forrest', function ($app) {

            // Config options
            $settings           = config('forrest');
            // ...
    }

    // ...
}
```

I noticed that `config('forrest')` was returning incorrect credentials.  `USERNAME` was wrong.  Although I defined `USERNAME` in the `.env` file, it was also defined by the OS (Windows login username).  The value passed along was the OS defined value&mdash;NOT what's in the `.env` file.

I simply changed `config/forrest.php` to

```php
// Only required for UserPassword authentication:
'username'       => env('SF_API_USERNAME'),
// Security token might need to be ammended to password unless IP Address is whitelisted
'password'       => env('SF_API_PASSWORD'),
```

and my `.env` file to

```
SF_API_USERNAME=jdoe@example.com
SF_API_PASSWORD=12345
```

Worked OK after that change.

**Comment by Fakerhardcore** [comment]
I got the same error, the solution was the IP restriction in salesforce:

Make sure the your Security > Network Access > Trusted IP Ranges has been set
From this post:
[https://stackoverflow.com/questions/12794302/salesforce-authentication-failing/29112224#29112224](https://stackoverflow.com/questions/12794302/salesforce-authentication-failing/29112224#29112224)

**Comment by arjunnarale** [comment]
https://stackoverflow.com/questions/12794302/salesforce-authentication-failing/29112224#29112224
