### ISSUE TITLE
Salesforce & TLS 1.0 phase-out (re-post)

### ISSUE THREAD

**Issue by Harrisonbro** [omniphx/forrest#147]
@omniphx I've just had another look into the TLS usage for our SalesForce instance and found that Forrest is indeed accessing SalesForce with the TLS 1.0 protocol, meaning that it will break in July when SalesForce turns off TLS 1.0 access.

I've gone into SalesForce and downloaded our login history, filtering by TLS 1.0, and found rows like this (some column omitted for brevity):

| Login Time       | Login Type        | Status  | Client Version | API Type | API Version | Login URL            | TLS Protocol | TLS Cipher Suite |
| ---------------- | ----------------- | ------- | -------------- | -------- | ----------- | -------------------- | ------------ | ---------------- |
| 11/04/2017 12:42 | Remote Access 2.0 | Success | N/A            | N/A      | N/A         | login.salesforce.com | TLS 1.0      | AES256-SHA       |

Can you think of which parts of Forrest might be accessing via the TLS 1.0 protocol and how we can work to update it? I'm happy to work on it and submit a PR if you point me in the right direction.

Thanks,
Harrison

- - - 

Note: I also posted this comment on my original issue #61 but that issue is closed so I've opened a new one in case it got missed. For context, SalesForce are contacting users saying this:

> _“Your org has been identified as having users or integrations still creating inbound connections to Salesforce using TLS 1.0 encryption protocol during the month of March._
> 
> _We want to remind you that Salesforce is requiring an upgrade to TLS 1.1 or higher by July 22, 2017. On that date we will disable TLS 1.0. To ensure your users and integrations will be able to connect to Salesforce after the disablement, please ensure you upgrade to TLS 1.1 or later before July 22, 2017.”_

**Comment by Harrisonbro** [comment]
Some resources which might be useful:

- https://help.salesforce.com/articleView?id=Salesforce-disabling-TLS-1-0
- [TLS 1.0 Disablement Readiness Checklist.pdf](https://github.com/omniphx/forrest/files/913094/SI.TLS.1.0.Disablement.Readiness.Checklist.pdf)

**Comment by omniphx** [comment]
Hi @Harrisonbro,

The TLS encryption is related to the encryption used by HTTPS on the web server that is running your app. Most likely you need to update OpenSSL and update some Apache/NGINX configurations. 

It is also unsupported in some older browsers, so make sure your [browser is up to date](https://security.stackexchange.com/questions/32817/why-dont-major-browsers-currently-support-tls-above-version-1-0).

Also just to triple check, my login tables are all authenticating using TLS 1.2.

Let me know if you need any assistance! Happy to help out

**Comment by Harrisonbro** [comment]
Ah ok, thanks for that clarification. I didn't know it was a server-level thing.

Do you know which Apache config settings I might need to look at? Is [this](http://serverfault.com/questions/314858/how-to-enable-tls-1-1-and-1-2-with-openssl-and-apache) the right sort of thing to be looking at?

**Comment by omniphx** [comment]
Yup, that should point you in the right direction. :+1:
