### ISSUE TITLE
Expected Forrest::describe() behavior

### ISSUE THREAD

**Issue by beneberle** [omniphx/forrest#150]
In the documentation, regarding output formats, I came across the below:
`
> Forrest::describe('Account',['format'=>'xml']);
`

When I try to use something similar, I get the following error:
```
ErrorException in Client.php line 159:
array_replace_recursive(): Argument #2 is not an array
in Client.php line 159
at HandleExceptions->handleError('2', 'array_replace_recursive(): Argument #2 is not an array', '../vendor/omniphx/forrest/src/Omniphx/Forrest/Client.php', '159', array('url' => 'https://xxx.salesforce.com/services/data/v39.0/sobjects', 'options' => 'Account'))
```

It appears that the describe() wrapper is only set up to return the full list of objects in your org and not a specific object as the documentation leads you to think.

Am I missing something? I suspect either the documentation needs updating, or the describe method needs to actually accept an $object parameter as indicated.

I can try to provide a pull request if this is indeed a valid issue.

**Comment by diggersworld** [comment]
I've just stumbled across this myself, it appears the underlying `describe` method only expects the `$options` array.

```php
/**
 * Describes all global objects available in the organization.
 *
 * @param array $options
 * @return array
 */
public function describe($options = [])
{
    $url = $this->getBaseUrl();
    $url .= '/sobjects';

    $describe = $this->request($url, $options);

    return $describe;
}
```

**Comment by diggersworld** [comment]
I have a fix working locally so I'll submit a PR this evening, unless it's already been fixed.

**Comment by omniphx** [comment]
Sorry about this mixup. Just poor documentation. The correct way to call this would be `Forrest::sobjects('Accounts', <options>);` The package is meant to be a wrapper for the Salesforce REST API, so you can always refer to the Salesforce documentation as a source of truth
