### ISSUE TITLE
Session store not set on request.

### ISSUE THREAD

**Issue by teguhsangra** [omniphx/forrest#152]
i have one issue, i'm running making file command laravel with forrest
and i have issue in the session strore 

is forrest cannot use in laravel console command ?

![screen shot 2017-06-07 at 3 23 37 pm](https://user-images.githubusercontent.com/6159999/26869080-526dd60e-4b95-11e7-9c7f-8a23d59d6997.png)

**Comment by SeunMatt** [comment]
@teguhsangra I also encountered the same problem while trying to call the authenticate method in a Unit Test. 
The point is, the session object requires the **web middleware to be active**.
So try making your calls in a controller that you have applied the web middleware or just use a test route for your testing.

**Comment by teguhsangra** [comment]
@SeunMatt  can i use the forrest send post to array 100 data?

**Comment by SeunMatt** [comment]
I have not tried it before though But I think so. Forrest is just a wrapper and is limited only by the Force.com REST API Limits. So go ahead and give it a try. You might want to consult the [API Docs](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_limits.htm) for more info.

**Comment by teguhsangra** [comment]
@SeunMatt  ok thnks sir 👍

**Comment by SeunMatt** [comment]
@teguhsangra You are welcome, sir. I think you should close the issue now.
