### ISSUE TITLE
undefined function env()

### ISSUE THREAD

**Issue by hasib32** [omniphx/forrest#153]
Hi, I'm trying to use your package for my Laravel 4 application. I just installed "omniphx/forrest": "^2.3" and I'm getting this error whenever I run any php artisan command: **{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalThrowableError","message":"Call to undefined function env()","file":"\/var\/www\\/vendor\/omniphx\/forrest\/src\/config\/config.php","line":20}}**

Is this package still supporting Laravel4.2?

Any help with that would be really helpful.

**Comment by omniphx** [comment]
Hey @hasib32, what service provider are you using for your app?

**Comment by omniphx** [comment]
Also if you are getting `undefined function env()`, probably means you don't have .env file in your project

**Comment by bubifengyun** [comment]
even I had add .env file, in which, every params was set. it also pops `undefined function env()`. Any help? Thank you.
