### ISSUE TITLE
EncryptedStore given, instance of Session expected.

### ISSUE THREAD

**Issue by JorgeAnzola** [omniphx/forrest#155]
Hello! I have this problem:

```
Type error: Argument 2 passed to Omniphx\Forrest\Providers\Laravel\LaravelSession::__construct() must be an instance of Illuminate\Contracts\Session\Session, instance of Illuminate\Session\EncryptedStore given, called in ...PATH.../vendor/omniphx/forrest/src/Omniphx/Forrest/Providers/BaseServiceProvider.php on line 74
```

I've found out [this issue](https://github.com/omniphx/forrest/issues/115). So I changed from `WebServer` to `UserPassword`, I've also changed my session driver from `file` to `database` but that didn't solve the problem.

Am I missing something?

I'm just calling this test method
```
	public function salesforceTest()
	{
		Forrest::authenticate();
	}
```

**Comment by omniphx** [comment]
Which version of Forrest are you using?

**Comment by JorgeAnzola** [comment]
I installed "omniphx/forrest": "^2.3",

**Comment by NikhilPardeshi** [comment]
hey, i am facing same issue

**Comment by omniphx** [comment]
Hi @NikhilPardeshi @JorgeAnzola, can't seem to reproduce this problem for you guys. Can you provide some more details about the type of Session/Cache configuration that is setup in your Laravel applications? Sorry for the long delay!

**Comment by omniphx** [comment]
I think this might be related to an upgrade the Laravel framework did in version 5.4 where the session handler is no longer being managed by a Symphony component. So if your framework is giving you an instance of Illuminate\Session\EncryptedStore when called `app('session')`, you'll either need to upgrade the framework or create your own service provider.

See section about Session: https://laravel.com/docs/5.4/upgrade
