### ISSUE TITLE
Session store not set on request

### ISSUE THREAD

**Issue by niko-afv** [omniphx/forrest#157]
Hi, i have next error message:

**"Session store not set on request"**

 when testing this line

`Forrest::authenticate();`

Because i'm trying execute that command in a cron (Job), without controller and session.

How can i solve this problem?

**Comment by niko-afv** [comment]
issue fixed with this config:

`'storage'        => [
        'type'          => 'cache', // 'session' or 'cache' are the two options
        ...
    ],`

**Comment by murwa** [comment]
I'm trying to use `cache` but I get this error 

> [Symfony\Component\Debug\Exception\FatalThrowableError]                                                                                                                   
  Type error: Argument 1 passed to Omniphx\Forrest\Providers\Laravel\LaravelCache::__construct() must implement interface Illuminate\Contracts\Cache\Repository, instance   
  of Illuminate\Config\Repository given, called in ...vendor/omniphx/forrest/src/Omniphx/Forrest/Providers/Laravel/ForrestServicePr  
  ovider.php on line 39  

I'm using Laravel 5.5

**Comment by omniphx** [comment]
@murwa, see #161

**Comment by Shaws-WD** [comment]
When I call Forrest_authenticate from a **cron** job I encounter this error   'Session store not set on request' with Forrest_authenticate .  So I changed Forrest config to use cache but a subsequent Laravel call fails.

`
SfSynchLogSummary::where('collection_type','=',$collectionTypeSpecified)->orderby('id', 'desc')			->first();
`
 gives this error
`
> PDOException: could not find driver 
> #0 /data/www/wd-dev/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(68): PDO->__construct('mysql:host=loca...', '..', '....', Array)`
> 

The code works normally when called via a http get. 
I am using Laravel 5.4.38
