### ISSUE TITLE
Please update package with Laravel 5.5

### ISSUE THREAD

**Issue by manoj30808** [omniphx/forrest#160]
Hi, i got a error like 

Omniphx \ Forrest \ Exceptions \ SalesforceException (403)
Salesforce response error

in laravel 5.5
![screenshot from 2017-10-28 12-24-08](https://user-images.githubusercontent.com/8142375/32132146-ce742ada-bbdb-11e7-9a5f-786932e255d4.png)

**Comment by GZamfirSMB** [comment]
I don't think that has anything to do with Laravel 5.5 . I am using laravel 5.5 and it works fine.
A 403 error is a "Forbidden" HTTP response. Make sure your are using the right Client ID and Client Secret of the App in Salesforce.

**Comment by manoj30808** [comment]
yes, you are right, it's not error of package.
package tried to call web api and my salesforce account in trial mode so account doesn't have access for it.
Do you know how can i call web api without purchase salesforce premium account.

**Comment by omniphx** [comment]
Hey @manoj30808, it should work for a developers account but if you're not using one of the supported versions there's no way to use the REST API

Editions with API Access:
Enterprise Edition
Unlimited Edition
Developer Edition
Performance Edition

Editions with no API Access:
Contact Edition
Group Edition
