### ISSUE TITLE
MissingTokenException: No Token Available

### ISSUE THREAD

**Issue by jeremiahC** [omniphx/forrest#162]
i tried to test if i can run query  with this route:

```
Route::get('/getApi', function() {
    Forrest::authenticate();
    return Forrest::query('SELECT Id From Account');
});
```

and when i go to the url route, i get this error:

![screenshot from 2017-11-17 18-21-29](https://user-images.githubusercontent.com/13476073/32942502-30a3b700-cbc4-11e7-9d2d-e43b8d23567e.png)

**Comment by omniphx** [comment]
Looks like you need to use `UserPassword` authentication. If you use `WebServer` you will need a callback route.
