### ISSUE TITLE
ErrorException in LaravelSession.php line 15:

### ISSUE THREAD

**Issue by powelljmp** [omniphx/forrest#164]
Hi, 
Struggling to get a clean install of Forrest up and running. Using L5.3

Error as follows: 

Argument 2 passed to Omniphx\Forrest\Providers\Laravel\LaravelSession::__construct() must be an instance of Illuminate\Contracts\Session\Session, instance of Illuminate\Session\Store given, called in /PhpstormProjects/p/vendor/omniphx/forrest/src/Omniphx/Forrest/Providers/Laravel/ForrestServiceProvider.php on line 36 and defined

Version 2.4
Routes defined with Web middleware. 
Config setup in forrest.php
Session driver 'file'
Running on local

**Comment by provun** [comment]
Hi

Did you manage to solve this issue?

**Comment by powelljmp** [comment]
The only way I could resolve it was to choose version "omniphx/forrest": "2.4.2",  this one then worked as expected

**Comment by provun** [comment]
Yeah thats what I have - what version of Laravel are you using?
