### ISSUE TITLE
Use of Forrest on Vanilla PHP

### ISSUE THREAD

**Issue by manuelRod** [omniphx/forrest#165]
Hello, I know you mentioned this: 

> While this package is built for Laravel, it has been decoupled so that it can be extended into any framework or vanilla PHP application. Currently the only support is for Larevel 4, 5 and Lumen.

But it would be really helpful to mention on the documentation how to use forrest on a vanilla php application. Should I create my own provider extending BaseServiceProvider.php?

**Comment by omniphx** [comment]
Hi @manuelRod,

Sorry, the documentation is lacking. For a vanilla implementation, you would just need to create an instance of either the WebServer or UserPassword classes (both of which extend the Client class).

The ServiceProvider classes are specific to Laravel, but you can use it a template for creating a custom implementation.

Currently, the only dependencies that are Laravel specific are;
```
$settings           = config('forrest');
$input     = new LaravelInput(app('request'));
$event     = new LaravelEvent(app('events'));
$encryptor = new LaravelEncryptor(app('encrypter'));
$redirect  = $this->getRedirect();
$storage   = $this->getStorage($storageType);
```

Happy to help!
