### ISSUE TITLE
How to check MissingTokenException omniphx/forrest

### ISSUE THREAD

**Issue by genjerdotcom** [omniphx/forrest#168]
Hi omniphx great Plugins thanks,

How to check MissingTokenException omniphx/forrest
please gimme example code

thanks

**Comment by kiamatt** [comment]
@omniphx This would help me out as well. I'm not getting any errors trying to authenticate but I can't seem to find a token in my cache, and I'm getting this exception as well.

**Comment by omniphx** [comment]
Hey guys, not sure I understand... do you want a way to retrieve the token? The token is encrypted and stored in your cache or session. It can be retrieved and decrypted with Laravel methods.

**Comment by VickG** [comment]
@omniphx I am not trying to retrieve the token...I am using following code

> \Forrest::authenticate();
> $query = \Forrest::query('SELECT Id FROM Account');
> dd($query);

and I get error:
throw new MissingTokenException('No token available');

**Comment by omniphx** [comment]
Will re-open if more information provided.
