### ISSUE TITLE
Return 404 when use Forrest::authenticate() in laravel 5.5

### ISSUE THREAD

**Issue by xt1991** [omniphx/forrest#170]
Dear Sir,

When I set up and config as well as your Doc, 

I got error

![image](https://user-images.githubusercontent.com/8934811/37071438-1d987d2c-21ef-11e8-9532-c32dd66a2e12.png)

My Sale Force App

![image](https://user-images.githubusercontent.com/8934811/37071717-75847238-21f0-11e8-8e60-a546e3d23b58.png)

My composer.json

![image](https://user-images.githubusercontent.com/8934811/37071641-0a9fd1d8-21f0-11e8-8181-775bd3c7c28b.png)

 My .env

![image](https://user-images.githubusercontent.com/8934811/37071667-31134bb0-21f0-11e8-887d-6d52b7f45b76.png)

My forrest 

![image](https://user-images.githubusercontent.com/8934811/37071691-4bf0acf2-21f0-11e8-9f0f-b91f184999bc.png)

Pls help me ,

Thank you !

**Comment by omniphx** [comment]
Hi @xt1991,

The login URL should be the Salesforce domains(most of the time it's `https://login.salesforce.com` or `https://login.salesforce.com`) and callback should your localhost
