### ISSUE TITLE
How often does the token expire and is it refreshed on its own?

### ISSUE THREAD

**Issue by aligajani** [omniphx/forrest#174]

**Comment by petplan-Pat** [comment]
The token is just thrown into the cache,  Salesforce expires the token after 1 hour, and does not auto refresh.  you could simply create a console command to call `Forrest::refresh()` X times an hour

**Comment by romanzpolski** [comment]
@aligajani this is off topic, but you authenticate with password or token ?

**Comment by aligajani** [comment]
I have just set the token to store forever.

**Comment by mathbles703** [comment]
Can you tell me what options you have set on your connected app? I am having issues making the token store_forever work correctly. It keeps timing out after a while. It doesn't seem to be consistent as to when it times out.

**Comment by aligajani** [comment]
```
 'storage'        => [
        'type'          => 'cache', // 'session' or 'cache' are the two options
        'path'          => 'forrest_', // unique storage path to avoid collisions
        'expire_in'     => 60, // number of minutes to expire cache/session
        'store_forever' => true, // never expire cache/session
```
