### ISSUE TITLE
Upsert on Salesforce record cries about Duplicate Record despite that Lead not existing at all, like anywhere?

### ISSUE THREAD

**Issue by aligajani** [omniphx/forrest#176]
I am using this package to Upsert a Lead onto Salesforce using a custom External ID which is the user's email stored in MySQL. Once a while, due to no reason whatsoever, Salesforce would cry out about a Duplicate Record when that email e.g. `legal@omitted.com` does't exist in Salesforce now or never. It simply doesn't exist anywhere. 

**Why would this happen?**

   ```
 GuzzleHttp\Exception\ClientException: Client error: `PATCH https://omitted-dev.my.salesforce.com/services/data/v42.0/sobjects/Lead/MySQL_Email__c/legal@omitted.com` resulted in a `400 Bad Request` response:
    [{"message":"You're creating a duplicate record. We recommend you use an existing record instead.","errorCode":"DUPLICAT (truncated...)
```

  [1]: https://github.com/omniphx/forrest

**Comment by omniphx** [comment]
@aligajani I'd recommend trying to upsert the same record into Salesforce using apex and see if you can reproduce the error.
