### ISSUE TITLE
Invalid Client ID

### ISSUE THREAD

**Issue by jeremiahsherrill** [omniphx/forrest#184]
`Client error: `POST https://login.salesforce.com/services/oauth2/token` resulted in a `400 Bad Request` response: {"error":"invalid_client_id","error_description":"client identifier invalid"}`

What could be causing this?  I know my consumer key is correct, I have double checked that.   Had issues with cert, fixed that.

**Comment by omniphx** [comment]
What are your config settings? Does the org have a custom domain name? Need a little more information from you to help out here.

**Comment by omniphx** [comment]
Nevermind, saw your other issue.
