### ISSUE TITLE
Language has to be specified in HTTP header.

### ISSUE THREAD

**Issue by Valkyrurr** [omniphx/forrest#185]
Can someone please tell me how to pass the language header in order to get a certain knowledgeArticle object? Based on available /forrest documentation, this issue's yet to be discussed. I wish to only use said wrapper in passing said header. Is this possible?

Please advise.

> Client error: `GET https://ap5.salesforce.com/services/data/v42.0/support/knowledgeArticles/kA07F0000006UOlSBZ` resulted in a `400 Bad Request` response:\n
> [{"errorCode":"MISSING_ARGUMENT","message":"Language has to be specified in HTTP header."}]\n

**Comment by omniphx** [comment]
I believe those are parameters required when sending a request to the knowledge article endpoint something `&language=en`
