### ISSUE TITLE
Option to output response in 'raw' format

### ISSUE THREAD

**Issue by omniphx** [omniphx/forrest#19]
No way to output format into a raw format. This would be useful to using the tooling api to output an xml or json response into a file.

Need to add a config option for raw output.

**Comment by rtconner** [comment]
Yeah I just passed in a 'format' option and used the Guzzle Response object how I needed.

```php
$response = Forrest::sobjects($resource,[
    'method'    => $method,
    'body'      => $params,
    'format'  => 'none',
]);
$content = (string) $response->getBody();
```

**Comment by omniphx** [comment]
Added documentation for this solution in Readme and config file.
