### ISSUE TITLE
Cannot update record, get generic "salesforce response error"

### ISSUE THREAD

**Issue by roblesterjr04** [omniphx/forrest#190]
Here is the request

```php
Forrest::sobjects('Chat_Transcript__c/aBq1J0000004MbS',[
	 'method' => 'put',
	 'body'   => ['Outcome__c' => 'Wrong']
]);
```

The user has the correct permissions, and object exists. Also have no issues creating new objects in this way. I just can't seem to update them.

**Comment by omniphx** [comment]
I think the Http method is `PATCH` not `PUT`

**Comment by roblesterjr04** [comment]
This was the example code

```php
$body = [
    'Name'  => 'Acme'
    'Phone' => '555-555-5555'];

Forrest::sobjects('Account/001i000000xxx',[
    'method' => 'put',
    'body'   => $body]);
```

I tried this again using the patch method and it worked. Would you please update the readme?

**Comment by omniphx** [comment]
Good catch! If you don't mind, that would be great. Looks like `PATCH` is used for both upsert and update. I didn't realize that previously.

**Comment by jsznap** [comment]
Can only update a record using the same method as an upsert but specifying the ID in the resource. Only issue is that there is no return on update. In fact, nothing can be returned after a patch operation. The update occurs but I get this error if I even try to get the raw guzzle reponse. 
```Call to a member function getBody() on null
```

**Comment by omniphx** [comment]
@jsznap looks like that is expected functionality until Salesforce changes it...  :/ https://success.salesforce.com/ideaView?id=08730000000aBr9AAE

**Comment by omniphx** [comment]
Upsert documentation has been updated.
