### ISSUE TITLE
HTTP method 'PATCH' not allowed with example from documentation

### ISSUE THREAD

**Issue by Koohiisan** [omniphx/forrest#191]
If I try to follow the upsert example I receive the 'patch not allowed' error.  I have set up a developer instance of Salesforce, created the App, and can read just fine.  Even from the workbench REST explorer this patch generates the same error.  Are there certain other required permissions needed?

I'm using the shared secret in my config, but not using username or password, in case that matters.

From debugging:
url => "https://na57.salesforce.com/services/data/v43.0/sobjects/Account"
body => "{"Phone":"555-555-1234","External_Id__c":"XYZ1234"}"
exception => "
    Client error: `PATCH https://na57.salesforce.com/services/data/v43.0/sobjects/Account` resulted in a `405 Method Not Allowed` response:\n
    [{"errorCode":"METHOD_NOT_ALLOWED","message":"HTTP Method 'PATCH' not allowed. Allowed are HEAD,GET,POST"}]\n
    "

**Comment by omniphx** [comment]
Does your user have the correct CRUD permissions in Salesforce? If the REST request isn't working on Workbench, it won't work with this library either.

**Comment by Koohiisan** [comment]
I think the permissions are correct.  I've given my user 'system administrator' access, and the app has 'full access' as well as 'access and manage your data' permissions.  What more is needed?

**Comment by Koohiisan** [comment]
Solved!  The issue was primarily due to the fact that I needed an external id field on whatever object I wish to use upsert with.  I assumed it was automatic.
