### ISSUE TITLE
Custom PHP use case?

### ISSUE THREAD

**Issue by saas786** [omniphx/forrest#194]
Hi there,

I am looking to find a suitable Salesforce client toolkit, and I stumbled upon your repo.

By the looks of it, I think this is what I was looking for.

But I am not using it with any framework (laravel, lumen none), and saw this issue 
https://github.com/omniphx/forrest/issues/165

and that's not v. helpful.

Specially if you are specifically mentioning its decoupled and doesn't depend on Laravel.

But I have spent two days trying to fulfill its dependencies hell, and initially tried to use Laravel, Illuminate packages, but it keeps getting heavier, and I didn't like it and it was not working either.

But then I decided to implement dummy classes on top of your interfaces, loading config file via require_once and so on. And I am able to call authenticate and generate url.

But I am not sure if its a solid / working code yet.

So I will really appreciate if you can implement the custom / vanilla php version alongside laravel / lumen implementations, so people like me, just can use it, without fiddling with interfaces / abstract classes, implementation etc.

Regards,
Syed

**Comment by omniphx** [comment]
I'll remove that piece of documentation. I originally had plans to implement this library for other php frameworks. If you made something work with a custom implementation, you are welcome to contribute it to the project.

**Comment by omniphx** [comment]
Documentation updated.
