### ISSUE TITLE
Error 411 when issuing GET request after a POST request 

### ISSUE THREAD

**Issue by tatohutch** [omniphx/forrest#197]
In the `handleRequest()` method of Client.php, the if statement of `if (isset($this->options['body'])` ignores the situation where 'body' may be set to null and GET requests should always have the body set to null.  When a POST request has just executed, the body (`$this->parameters['body']`) is still set to the body of the previous request and has to be set to null for the GET request to succeed.  Otherwise, a 411 "Length Required" response is received from Salesforce.

A suggested fix would be to replace the if conditional with:
`$this->parameters['body'] = empty($this->options['body']) ? null : $this->formatter->setBody($this->options['body']);`

**Comment by omniphx** [comment]
To clarify, this is happening when:
Forrest::Post('post/request', ['body' => 'payload']
Forrest:Get('get/request');

And the 'body' is set in the first `Post` request but not unset in the subsequent `Get` request?

**Comment by tatohutch** [comment]
Correct.

**Comment by leo108** [comment]
@omniphx any update?

**Comment by omniphx** [comment]
@tatohutch, @leo108  any chance you could provide some more information to help me reproduce this?

The following snippet didn't throw any 411 errors:
```
    $externalId = 'XYZ1236';

    $result = Forrest::sobjects('Account/marty__External_Id__c/' . $externalId, [
        'method' => 'patch',
        'body'   => [
            'Name'  => 'Acme',
            'Phone' => '555-555-6666'
        ]
    ]);

    Forrest::query('SELECT Id FROM Account');
```
I also did a `var_dump` of `$this->options['body']` it appears to only be set for the upsert (POST) request and not for the query (GET) request.

**Comment by tatohutch** [comment]
Marty,

I just tested my branch that was receiving the 411 errors before and it is
working as expected now.  Perhaps Salesforce changed something on their
side.  Either way, it does not appear to require any changes to the Forrest
library as far as I can tell.

Thank you,
Lance

**Comment by omniphx** [comment]
Very strange. Let me know if it pops up again.

**Comment by rajjanorkar** [comment]
It's happening to me as well when i do 

`SObjects::object('Lead', $params)->save();`

and immediately after above i do 

`SObjects::object('Lead')->find('00Q6325345D000001HROeUAO');`

I get 411 

`Client error: `GET https://afdasfasf.salesforce.com/services/data/v46.0/query?q=select+Id%2C+Name%2C+FirstName%2C+LastName%2C+Phone%2C+Email%2C+OwnerId%2C+contact_type__c%2C+Nationality__c%2C+Company%2C+Campuses__c%2C+Agent_Account__c%2C+LeadSource%2C+Address%2C+prospective_agency_location__c%2C+prospective_agency_market__c%2C+Status+from+Lead+where+Id+is+null+limit+1` resulted in a `411 Length Required` response:`

**Comment by rajjanorkar** [comment]
Fixed this bug here - https://github.com/omniphx/forrest/pull/222
