### ISSUE TITLE
Is the document wrong for upsert?

### ISSUE THREAD

**Issue by snowwolf007cn** [omniphx/forrest#198]
> Upsert a record
> Update a record with the PATCH method and if the external Id doesn't exist, it will insert a new record.
> 
> $body = [
>     'Phone' => '555-555-5555',
>     'External_Id__c' => 'XYZ1234'];
> 
> Forrest::sobjects('Account',[
>     'method' => 'patch',
>     'body'   => $body]);

I follow this example and got a 405 error from the salesforce server side. After dig deeper into the source code, I found that it didn't generate the resource url properly according salesforce API reference.

```
        $response = Forrest::sobjects(
          'Contact/' . self::CONTACT_EXTERNAL_ID_FIELD . '/' . $externalId,
          [
              'method' => 'patch',
              'body'   => $data,
          ]
        );

```
codes above can be run properly.

**Comment by omniphx** [comment]
Thanks for pointing this out @snowwolf007cn, I updated the documentation.
