### ISSUE TITLE
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

### ISSUE THREAD

**Issue by nhantrandev96** [omniphx/forrest#199]
I have an error:
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

I use authenticate 'WebServer'. When using callback function, I get the same error.
Hope everyone helps. Thank you.

**Comment by dagariyaharsh** [comment]
Working fine with 'UserPassword' but not working with 'WebServer' and got the same error which mentioned above.
Thanks

**Comment by VickG** [comment]
I am getting this error when using UserPassword as authentication method. 
I was not able to get it work with WebServer authentication either.

**Comment by dagariyaharsh** [comment]
Can you please tell me, What exact error you are getting?

**Comment by VickG** [comment]
@dagariyaharsh cURL error 3: malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by shafiqkr18** [comment]
same error here, if we are not using ` Forrest::authenticate();` then token session error comes

**Comment by omniphx** [comment]
hi @VickG , can you check to see if you are having the same issue as https://github.com/omniphx/forrest/issues/183? Otherwise, please share your `config/forrest.php` and route setup. Thanks!

**Comment by omniphx** [comment]
A similar error message that was appearing in #183. Documentation has been improved on the README: https://github.com/omniphx/forrest#configuration
