### ISSUE TITLE
authenticate issue

### ISSUE THREAD

**Issue by shafiqkr18** [omniphx/forrest#201]
I have config/forrest.php file code

    'authentication' => 'UserPassword',

    `'credentials'    => [
    //Required:
    'consumerKey'    => env('3MVG9tzQRhEbH_K2Q68w...'),
    'consumerSecret' => env('9458CB7D...'),
    'callbackURI'    => env('https://login.salesforce.com/services/oauth2/callback'),
    'loginURL'       => env('https://login.salesforce.com'),

    // Only required for UserPassword authentication:
    'username'       => env('email@email.com'),
    // Security token might need to be ammended to password unless IP Address is whitelisted
    'password'       => env('Abc@123'),
],`

Here is route code

      `Route::get('/authenticate', function()
          {
         Forrest::authenticate();
         return Redirect::to('/');

    });`
I am getting this error

cURL error 3: malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

Note: I do not want this authentication, can i do it by username and password directly without running this authenticate method?

**Comment by omniphx** [comment]
Hi @shafiqkr18, looks like this is the same issue happening in https://github.com/omniphx/forrest/issues/183

Basically, you should need to setup an environment variable called `CONSUMER_KEY` or just pass the api credentials as strings

So this is one option: `'consumerKey' => ''3MVG9tzQRhEbH_K2Q68w'`

Or update `.env` file: `CONSUMER_KEY=3MVG9tzQRhEbH_K2Q68w`

Hope that helps!

**Comment by omniphx** [comment]
Documentation steps have been added to the readme
