### ISSUE TITLE
Custom Headers

### ISSUE THREAD

**Issue by Pashedu** [omniphx/forrest#204]
Is there any way I can set a custom header? After quick code look through I haven't find easy way.

**Comment by coryrose1** [comment]
Hi @Pashedu,

I'm looking for the same functionality, I also posted [an issue](https://github.com/omniphx/forrest/issues/203) in regards to setting the header so I can tell Salesforce to run Lead Assignment rules when created Leads.

**Comment by omniphx** [comment]
Hi @Pashedu,

If you update to the latest 2.4.7 release, you should now be able to set custom headers. Please see the README or #203 for more details.
