### ISSUE TITLE
Connecting to more than one salesforce instance?

### ISSUE THREAD

**Issue by jeremiahsherrill** [omniphx/forrest#206]
Already connecting to one salesforce instance using the user password method.  How can I connect to a seperate salesforce instance?  We currently use Forrest::Authenticate which connects to our partner org, but we also need to connect to our main production org.   What would be the best way to go about this?

**Comment by omniphx** [comment]
Hey @jeremiahsherrill, you would need multiple instances of the Forrest object with different configurations injected to support connecting to multiple Salesforce environments within the same app.... so kinda tricky but is possible.

To be honest, I built this library to support an app that utilizes Oath2 and threw in the UserPassword to help with debugging. If you find an elegant way to accomplish multiple instances, please document/contribute I know others would appreciate it.

**Comment by omniphx** [comment]
https://github.com/omniphx/forrest#creating-multiple-instances-of-forrest
