### ISSUE TITLE
MissingTokenException: No token available in 'cache' storage

### ISSUE THREAD

**Issue by megusta420** [omniphx/forrest#207]
Hi guys! Already saw similar issues but "Forrest::authenticate()" ain't helps (used it in artisan tinker).
Here is an error:

> Omniphx\Forrest\Exceptions\MissingTokenException: No token available in 'cache' storage in /var/www/html/vendor/omniphx/forrest/src/Omniphx/Forrest/Providers/Laravel/LaravelStorageProvider.php:39

Here is storage from forrest.php:
```
    'storage'        => [
        'type'      => 'cache', // 'session' or 'cache' are the two options
        'path'      => 'forrest_', // unique storage path to avoid collisions
        'expire_in' => 999999, // number of minutes to expire cache/session
    ],
```

Here are credentials from forrest.php:
```
    /*
     * Options include WebServer or UserPassword
     */
    'authentication' => 'WebServer',

    /*
     * Enter your credentials
     * Username and Password are only necessary for UserPassword flow.
     * Likewise, callbackURI is only necessary for WebServer flow.
     */
    'credentials'    => [
        //Required:
        'consumerKey'    => env('SALESFORCE_CONSUMER_KEY'),
        'consumerSecret' => env('SALESFORCE_CONSUMER_SECRET'),
        'callbackURI'    => env('SALESFORCE_CALLBACK_URL'),
        'loginURL'       => env('SALESFORCE_LOGIN_URL'),

        // Only required for UserPassword authentication:
        'username'       => env('USERNAME'),
        // Security token might need to be ammended to password unless IP Address is whitelisted
        'password'       => env('PASSWORD'),
    ],
```
Change to "UserPassword" auth type in forrest.php aint works too:
```GuzzleHttp\Exception\ClientException: Client error response [url] https://login.salesforce.com/services/oauth2/token [status code] 400 [reason phrase] Bad Request in /var/www/html/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89```

This one shows "null":
```
Route::get('token', function(){
    Forrest::authenticate();
    dd(Session::get('forrest_token')); 
});```

**Comment by omniphx** [comment]
Looks like you have storage type set to `cache`. Can you try `dd(Cache::get('forrest_token'));`?

**Comment by megusta420** [comment]
@omniphx sorry it's my config. My colleague changed to 'session' and checked if key is in Session after Forrest:auth().

**Comment by omniphx** [comment]
@megusta420 does this you have resolved this?

**Comment by megusta420** [comment]
@omniphx hmm seems problem gone after i reinstalled app which i maintain. We may close this issue, will reopen if issue will happen again. Thanks.
