### ISSUE TITLE
What throws the MissingResourceException?

### ISSUE THREAD

**Issue by roblesterjr04** [omniphx/forrest#208]
I am working with a salesforce staging/sandbox environment. I've never seen this exception thrown in production but we get it intermittently with sandbox. There's no consistency in when we get it or under what conditions. Can you shed some light on the context of the exception? I kind of understand it has to do with the storage repo for the token, but i don't understand under what conditions the repo is not available. Thanks!

```
Omniphx\Forrest\Exceptions\MissingResourceException: No resources available in /home/~*~*~*~/vendor/omniphx/forrest/src/Omniphx/Forrest/Repositories/ResourceRepository.php:36
```

**Comment by omniphx** [comment]
The resource repo is just a cache of this request: `Forrest::resources();` which tells the app which REST APIs it has access to. More info here: https://github.com/omniphx/forrest#api-requests

After storing "resources", the library allows you to call any of those resources methods using the magic `__call()` method. If Salesforce decides to create a new API called `EinsteinPrediction` or something similar. You'll be able to consume it with `Forrest::EinsteinPrediction()`.

That exception is basically saying for some reason there is nothing in your storage that has the name "resource". Maybe it's possible the cache or session has been cleared?

I included the exception message to provide more information than a null pointer exception, but seems like a better solution is for the library to retry the `resources()` request if it doesn't exist.

**Comment by roblesterjr04** [comment]
Do you have any reason to believe that this will only occur to me in SandBox environments? Like I said, I've never encountered it in production.

**Comment by omniphx** [comment]
I would test the `Forrest::resources();` in your sandbox environment. If it returns results, then my guess is that something is happening in your Session/Cache settings.

Does this happen all the time or is it intermittent?

**Comment by roblesterjr04** [comment]
Intermittent in the sandbox environment.

**Comment by roblesterjr04** [comment]
Confirmed its not just sandbox - will troubleshoot.

**Comment by bgenoa** [comment]
I've been seeing the same issue in the last week or two and it may be related to issue #197.  I'm seeing sporadic 411 length required errors on \Forrest::authenticate(); and then after this occurs I start receiving the missing Resource Exception errors.
