### ISSUE TITLE
Can't save new record- returns a '400 Bad Request` response

### ISSUE THREAD

**Issue by stzahi** [omniphx/forrest#209]
When trying to save a new record in a brand new SF custom object I gets this error:
"Salesforce response error: Client error: POST https://BLABLA.my.salesforce.com/services/data/v46.0/sobjects/ObjectName__c` resulted in a 400 Bad Request response"`

From Salesforce developer guide, 400 status code is being returned when:

400 | The request couldn’t be understood, usually because the JSON or XML body contains an error.

`\Forrest::sobjects('CustomObject__c',[
         'method' => 'post',
         'body'   => $recordData
     ]);        `

Your help will be appreciated,
And thank you for sharing this cool feature!

**Comment by omniphx** [comment]
The response says there is an error in the post body. Can you share a sample of what is stored in `$recordData`?

**Comment by stzahi** [comment]
`array:5 [
  "isCharged__c" => "false"
  "TimeToExecute__c" => "2019-06-12T05:52:30.000Z"
  "sum__c" => "200"
  "payments__c" => "1"
  "Donator__c" => "0031t00000MpQbwAAF"
]`

**Comment by stzahi** [comment]
@omniphx , BTW, there is no field in this object that is set as "required" etc...
The "Name" record of the field is automatic generated number,
I've tried to send the same request with only one field "isCharged__c => false" and I get the same error message.

Please help me... I'm desperate.

**Comment by stzahi** [comment]
@omniphx here is an update:
The reason for the error was a validation rule that was active on this object and the requirements didn't fit the structure of the data.
I don't understand why Salesforce returns such a poor error message, and why don't they send the error message that was supplied by that validation rule.
SHAME ON THEM.
Thank you for trying to help me!
