### ISSUE TITLE
How to insert multiple records in one call?

### ISSUE THREAD

**Issue by i-ira** [omniphx/forrest#210]
Does This Library support bulk inserts? For instance, If i wanted to insert multiple records of an `Account` object in one call, do I have to fire a `post` method for every record?

```
Forrest::sobjects('Account',[
    'method' => 'post',
    'body'   => ['Name' => 'Dunder Mifflin']
]);
```

or can I insert these in bulk?

**Comment by mathbles703** [comment]
Seems to be that way. I've had to do this in my app. A little bit extra performance is that once you have the data in your client in an array, add a flag on the records that are actually changed so you're not updating records that haven't actually been changed.

**Comment by omniphx** [comment]
Try using the composite resource: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_composite_sobjects_collections_create.htm

Should work with: `Forrest::composite('sobjects', 'post', $body)`

You can also use the batch api: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/resources_composite_batch.htm

Batch syntax: `Forrest::composite('batch', 'post', $body)`

**Comment by i-ira** [comment]
well, that works. Thanks!
