### ISSUE TITLE
Authentication Error

### ISSUE THREAD

**Issue by cdavila1990** [omniphx/forrest#211]
I have followed all the steps for setup however I am getting this error when I try to reach the authenticate route.

_ErrorException in LaravelSession.php line 15:
Argument 2 passed to Omniphx\Forrest\Providers\Laravel\LaravelSession::__construct() must be an instance of Illuminate\Contracts\Session\Session, instance of Illuminate\Session\Store given, called in /var/www/dist.com/vendor/omniphx/forrest/src/Omniphx/Forrest/Providers/Laravel/ForrestServiceProvider.php on line 36 and defined_

My research on this error is coming up empty. Please help. Thanks

**Comment by omniphx** [comment]
What version of Laravel are you using?

**Comment by cdavila1990** [comment]
5.2
After posting the issue I noticed it has been a problem in the past for others as well. I tried downgrading to version 2.4.2 because someone said it worked for them. Still nothing.

**Comment by omniphx** [comment]
Looks like Laravel updated this interface back in 5.4 and 5.24.

You can try updating your Laravel project to 5.24 or try version 2.3.1 of this library.

**Comment by cdavila1990** [comment]
I went down to 2.3.1 and this is the new error. Is there anything I'm missing in the stack trace that you can see?

![error](https://user-images.githubusercontent.com/38474858/60345880-9b7bf800-997f-11e9-9baf-3a5ed0df6cd9.PNG)

**Comment by omniphx** [comment]
Hm... real hard to deal with these backwards compatibility issues. What is the exact Laravel version you are using?

**Comment by omniphx** [comment]
Maybe try 2.36?

**Comment by cdavila1990** [comment]
My exact laravel version is 5.2.45.

When I remove the session variables from LaravelSession.php I'm able to pass through to salesforce.com for logging in. 
![LaravelSession screenshot](https://user-images.githubusercontent.com/38474858/60352261-0d0e7300-998d-11e9-8a34-ff632b5554ed.PNG)

However this is the error I get when I attempt to log in. 
![salesforcelogin error](https://user-images.githubusercontent.com/38474858/60352253-0849bf00-998d-11e9-8f85-9e2abd4252e4.PNG)

**Comment by omniphx** [comment]
`unsupported_grant_type` is actually a Salesforce response, so that's a good sign. Could you share what you have configured?

**Comment by omniphx** [comment]
Possible it might have to do with the login url you are using: https://salesforce.stackexchange.com/questions/223205/sfdx-grant-type-not-supported

**Comment by cdavila1990** [comment]
`CALLBACK_URI=https://login.salesforce.com/services/oauth2/token
LOGIN_URL=https://login.salesforce.com`

**Comment by cdavila1990** [comment]
What would you like to see as far as configuration goes?

**Comment by omniphx** [comment]
Callback URI is what endpoint Salesforce is supposed to send the response. For instance, it will probably be `localhost:8080/callback` or similar for local development
