### ISSUE TITLE
Revoke fails. Return 400

### ISSUE THREAD

**Issue by mathbles703** [omniphx/forrest#213]
Trying to get Forrest::revoke() and it returns a 400 Bad request. 

```
Client error: `POST https://test.salesforce.com/services/oauth2/revoke` resulted in a `400 Bad Request` response:
error=unsupported_token_type&error_description=this%20token%20type%20is%20not%20supported
```

I need to use this for logout functionality / disabling users. I am calling it like this

```$router->get('/revoke', function() use ($router){
    Forrest::revoke();
});
```

Testing it like this doesn't seem to work

**Comment by mathbles703** [comment]
('post', 'https://test.salesforce.com/services/oauth2/revoke', array('headers' => array('content-type' => 'application/x-www-form-urlencoded'), 'form_params' => array('token' => array('access_token' => 'REDACTED', 'instance_url' => 'REDACTED', 'id' => 'REDACTED', 'token_type' => 'Bearer', 'issued_at' => '1562772353271', 'signature' => 'REDACTED')), 'synchronous' => true))

**Comment by rohitasare7** [comment]
I am facing the same issue, using the custom domain, any fix? @omniphx
