### ISSUE TITLE
Dynamic Salesforce Authentication

### ISSUE THREAD

**Issue by reymark-torres** [omniphx/forrest#217]
Is there a way to authenticate using this package by parsing a username & password in the request instead of the static username/password in the config file when calling _Forrest::authenticate_?

Basically my issue is that I have a separate front end (UI) & back end (API) projects. So the **Web Server authentication flow** couldn't be the use case since I am using AJAX calls to the API side so it wouldn't let this package to redirect to the Salesforce login page.

Really appreciate your suggestion.

Thanks.

**Comment by reymark-torres** [comment]
Closed this and use [SOAP Authentication Flow](https://github.com/omniphx/forrest#soap-authentication-flow).

**Comment by i-ira** [comment]
> Closed this and used [SOAP Authentication Flow](https://github.com/omniphx/forrest#soap-authentication-flow).

just curious, how did you implement the SOAP flow? how did you set your authentication route and callback action once making the AJAX call?

**Comment by reymark-torres** [comment]
Here's what I did:
1. Changed the forrest.php config file authentication key into UserPasswordSoap as value.
2. For authentication I just set the loginURL, username & password into Forrest authenticateUser method. I just created a basic POST AJAX call that will trigger this code:
	```
		Forrest::authenticateUser(
            config('forrest.credentials.loginURL'),
            request('username'),
            request('password')
        );
	```
Then that's it. If you try to die and dump cache('forrest_token'), you should have one after authenticating.

P.S. You just need a Salesforce account that has ENABLE API option to work on any of the flow.

Cheers.
