### ISSUE TITLE
SalesforceException format

### ISSUE THREAD

**Issue by mathbles703** [omniphx/forrest#220]
Is it possible to make the salesforceException return JSON instead of the html that gets returned? I require this for an internal API.

Anytime you hit a salesforce error or validation it will always return a giant block of html with the error embedded. I'd prefer just default to JSON

**Comment by mathbles703** [comment]
This is specifically when the API is not authenticated and it hits a 500 error. Not sure how to override this since it's not even entering the method I defined yet

**Comment by omniphx** [comment]
Can you provide some steps for reproducing this? As well as what you have configured in your routes/config
