### ISSUE TITLE
Using 2 Salesforce sessions concurrently

### ISSUE THREAD

**Issue by stzahi** [omniphx/forrest#228]
Hi!
Can I use 2 instances of the library concurrently?
I need one for UserPassword auth method, and the second one for a regular web server auth flow.

Will be glad to get a direction to solve this.

Thanks a lot!

**Comment by omniphx** [comment]
Currently, the library is built as a Service Provider. If you only needed 1 additional connection type, you could spin up your own Service Provider by copy/pasting: `src/Omniphx/Forrest/Providers/Laravel/ForrestServiceProvider.php`.

You would also need to inject an array for the configuration.

If you need the ability for `n+1` connections, then some major refactoring would probably be needed to this library to allow for something like Service Containers (similar to how [jsforce ](https://jsforce.github.io/) connections are just objects)

**Comment by stzahi** [comment]
Thank you for the detailed ansert

**Comment by omniphx** [comment]
I know you were asking for a specific situation with WebServer + UserPassword instances (still haven't solved for that), but for anyone else. There is now the ability to create multiple instances of UserPassword.
