### ISSUE TITLE
Laravel 7.x support

### ISSUE THREAD

**Issue by jonnott** [omniphx/forrest#248]
Due to the dependency on illuminate/* components of "~6.0" .. Laravel 7.x needs composer to downgrade forrest to v2.6.

To allow support for the latest versions (2.7.x) of forrest in Laravel 7.x, please update this requirement to "~6.0|~7.0" for all illuminate/* libs.

**Comment by omniphx** [comment]
Makes sense, feel to a PR. Otherwise, I'll try to take care of this soon.
