### ISSUE TITLE
I can't found the class use Forrest

### ISSUE THREAD

**Issue by rivara** [omniphx/forrest#253]
Hi 
i know something it's wrong in this way , i have the next instances class "use  Omniphx\Forrest;"
but not recognize the methods , for example Forrest::versions(); 
Please help me

**Comment by javier-gocubesoftware** [comment]
How did you make it work?

I have tried:
use Forrest;
use Omniphx\Forrest\Providers\Laravel\Facades\Forrest;
use Omniphx\Forrest;

No success
