### ISSUE TITLE
Schedule Task to Pull Updated Data

### ISSUE THREAD

**Issue by JasonMaitlen** [omniphx/forrest#256]
I'd like to schedule a task that regularly pulls updated fields for Accounts, Users, and a custom object in Salesforce to be used in the Laravel application. I have users logging into the front-end using the WebServer authentication method which works as expected, but I'd like a privileged account to be used in the scheduled task to pull that updated information. I assume I'd need to use the UserPassword authentication method for that pull and use the credentials stored in the environment variables.

So far, the only way I can get this to work is if I authenticate with my user in the front-end then quickly (within a minute or so) start the scheduled task. After that time it doesn't error, but won't pull any data. What am I doing wrong?

Here's my code for Kernel.php:
```
<?php

namespace App\Console;

use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;
use \App\User;

class Kernel extends ConsoleKernel
{
    /**
     * The Artisan commands provided by your application.
     *
     * @var array
     */
    protected $commands = [
        //
    ];

    /**
     * Define the application's command schedule.
     *
     * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
     * @return void
     */
    protected function schedule(Schedule $schedule)
    {
        // load User data from Salesforce
        $schedule->call(function () {
            $forrest = app()->make('forrest');
            $sqlUsers = $forrest->query('SELECT Id, AccountId, Name, Username FROM User');
            
            foreach ($sqlUsers['records'] as $row) {
                $user = new \App\User;
                $user->id = $row['Id'];
                $user->account_id = $row['AccountId'];
                $user->name = $row['Name'];
                $user->username = $row['Username'];
                $user->save();
            }
            
        })->everyMinute();
    }

    /**
     * Register the commands for the application.
     *
     * @return void
     */
    protected function commands()
    {
        $this->load(__DIR__.'/Commands');

        require base_path('routes/console.php');
    }
}
```

**Comment by omniphx** [comment]
Hi @JasonMaitlen this is a good use case for [JWT authentication](https://github.com/omniphx/forrest#jwt-authentication-flow). Essentially it's a way to pre-authorize a user to run jobs like in the background. Was just recently added in v2.10.
