### ISSUE TITLE
Query returns null

### ISSUE THREAD

**Issue by letournj** [omniphx/forrest#257]
Hi,

I would like to get the result of a query

`Forrest::jobs('query/XXXXXXXXXX/results...`

But it returns null, I tried with postman, it's working.

How can I get the results of my query, or the CSV ?

Thanks for helping me :)

**Comment by omniphx** [comment]
What is the API call that you're making with postman?

**Comment by letournj** [comment]
The same URL, jobs/query/QueryId/results

**Comment by letournj** [comment]
`dd(\Omniphx\Forrest\Providers\Laravel\Facades\Forrest::jobs('query/XXXXXXXXX/results',
		['method'=>'get','headers' => [
			'Content-Type' => 'text/csv',"Accept"=>"text/csv"
		],]));`
	It returns NULL
	
	`dd(Forrest::query('select name from Account'));`

It's working
