### ISSUE TITLE
Pagination?

### ISSUE THREAD

**Issue by Claymm** [omniphx/forrest#26]
Is there any way to use a Paginator with this?

**Comment by Claymm** [comment]
Well I know that you can only get 2000 results pre request with Salesforce.
How this is handled by the package?
Also would it be possible to paginate the result of a query every 10 rows for example? There is a OFFSET and LIMIT thing in SOQL but they both can't go further than 2000.

**Comment by Claymm** [comment]
Also do you handle the "nextRecordsUrl" parameter if the query returns more that 2000 results?

**Comment by omniphx** [comment]
Gotcha. Here's some more information about retrieving the nextRecordURL: http://www.salesforce.com/us/developer/docs/api_rest/index_Left.htm#CSHID=using_resources_working_with_searches_and_queries.htm|StartTopic=Content%2Fusing_resources_working_with_searches_and_queries.htm|SkinName=webhelp

I'll probably need to create a method similar to the queryMore() in the SOAP API.

Will take care of this when I get a chance.

**Comment by Claymm** [comment]
(thumbsup)

**Comment by omniphx** [comment]
Merged PR #29 to fix this issue. Will need to add documentation soon.
