### ISSUE TITLE
Related Objects

### ISSUE THREAD

**Issue by jayomayan** [omniphx/forrest#260]
Does anyone know how to query the related objects.

Example: Query the Contact's related Opportunities.

**Comment by omniphx** [comment]
Hi @jayomayan, this question is probably better suited for the [Salesforce Stackexchange](https://salesforce.stackexchange.com/) or the [SF Developer forums](https://developer.salesforce.com/forums?dc=Apex_Code_Development#!/feedtype=RECENT&criteria=ALLQUESTIONS&)

Generally, most queries will look like this for child relationships:
`SELECT Id, (SELECT Id FROM Cases) FROM Account`

Or for parent relationship:
`SELECT Id, CreatedBy.Name FROM Account`
