### ISSUE TITLE
Config gets "trimmed" by something…

### ISSUE THREAD

**Issue by mityukov** [omniphx/forrest#262]
I wanted to ask if it's expected behavior (e.g., some service provider cuts "intimate" configuration from the variable).

Here's the config:
![image](https://user-images.githubusercontent.com/1751910/90068204-504ab300-dd01-11ea-897c-d612f638c090.png)

Here's the tinker:
![image](https://user-images.githubusercontent.com/1751910/90068239-60fb2900-dd01-11ea-8989-89442a8fcf2c.png)

not only `credentials` is `null`, but `authentication` is different as well…

I've tried  `php artisan config:clear` multiple times — nothing helps…

**Comment by mityukov** [comment]
It looks that `roblesterjr04/EloquentSalesForce` overwrites 'forrest' configuration…

**Comment by raphaelmsr** [comment]
Same issue here.. so what do we do ??

**Comment by omniphx** [comment]
As @mityukov pointed out, sounds like EloquentSalesforce is overwriting the configuration. There are some details in that package on how to configure forrest: https://github.com/roblesterjr04/EloquentSalesForce#configuration
