### ISSUE TITLE
'format' option is set too late in handleRequest()

### ISSUE THREAD

**Issue by Zaphell** [omniphx/forrest#264]
Hi @omniphx ! Love the library and the community behind it!

I was playing around with Bulk API 2.0, which requires me to change the 'format' (Formatter) from 'none' to 'json', and there's a small issue with how the Formatter is set in the handleRequest() method:

https://github.com/omniphx/forrest/blob/master/src/Omniphx/Forrest/Client.php#L214

The problem is that lines 200 and 205 above use Formatter methods. In my case I had the ```'format' => 'none'``` option for a request, then my subsequent request had a ```'format' => 'json'``` array, with a ```'body' => []``` parameter. Since the 'none' formatter is still set on line 205, my 'body' isn't passed as JSON, and an error is thrown.

Would you agree: lines 211-213 should be at the top of the handleRequest() method?

Thanks!

**Comment by omniphx** [comment]
Hey @Zaphell, can you check if #268 solves your issue? You'll need to install`dev-master`

**Comment by omniphx** [comment]
Bugfix was released in Version 2.10.0. Feel free to reopen if it's still an issue.

**Comment by Zaphell** [comment]
Seems like I can't push a branch of my own to this repo... I ended up extending the Omniphx for my project, and changing things differently than what was done in issue #268 .
Here's a screenshot of the code I changed:
![image](https://user-images.githubusercontent.com/616264/95038176-866e3880-069b-11eb-943e-cb64c221b942.png)

My commit message was going to be: "If 'format' option exists in Forrest request, it takes precedence. Don't set formatter if correct one is already set."

**Comment by omniphx** [comment]
Yea, the way you make PRs in github is not super intuitive. You have to fork the entire repo, push up your changes up to the forked repo and then you'll have an option to create a PR. Feel free to give it another shot if you want some open source credit :)
