### ISSUE TITLE
How to convert lead to an account?

### ISSUE THREAD

**Issue by kalanaRukshan** [omniphx/forrest#273]
How can I convert the lead to the account? can you please give an example

**Comment by omniphx** [comment]
Unfortunately, there's no way to convert a lead with the Salesforce REST API which this library is a wrapper for.

You can create a custom Apex REST call as mentioned here: https://stackoverflow.com/questions/19663119/is-there-any-rest-service-available-in-salesforce-to-convert-leads-into-accounts

You can then call your custom endpoint using this guide: https://github.com/omniphx/forrest#custom-apex-endpoints

**Comment by kalanaRukshan** [comment]
Thanks
