### ISSUE TITLE
Feature Reqest - Option to persist token without session.

### ISSUE THREAD

**Issue by rtconner** [omniphx/forrest#28]
In our system we literally are calling the SF API from an API of our own. So session based token storage does not persist at all. A cache or file or database storage of the token would be useful for persistence (and thus speed).

**Comment by rtconner** [comment]
I'll probably build this at some point. Just wanted to get the request in so you know about it.

**Comment by omniphx** [comment]
Not sure if it's related to your problem, but I referred to something similar in issue #13. Basically Laravel's session driver allows you to use different storage formats (database, cache, cookie, files, etc.)

**Comment by rtconner** [comment]
Ok I'll keep that in mind. If I do anything here, I'll try to be smart about it.

**Comment by omniphx** [comment]
FYI, renamed "SessionInterface" to "StorageInterface". Still using Laravel's Session driver for the package, but thought it might cause confusion since the codebase doesn't really care how the token is stored.

**Comment by rtconner** [comment]
As I'm working on this .. is there any reason why Client.php and Resource.php are two separate classes? I feel like they should be merged.

**Comment by omniphx** [comment]
I initially set it up this way so that the differences classes would be injected into the Client.php as services. However now that it's just extending each parent class, it makes more sense to merge them.

**Comment by rtconner** [comment]
Can you please code review that commit and let me know if you see anything off?

**Comment by omniphx** [comment]
Looking good! I like how you made the storage class extendable for encrypting the tokens. The option to configure the storage path is a great idea as well.

Feel free to merge when you're ready.

Also, I saw you added Laravel 4.0 to the composer file. Will this cause conflicts with people that have upgraded to 5.0? I quickly skimmed the release notes and couldn't find anything that might cause compatibility issues. This is where integration testing would be valuable.

**Comment by rtconner** [comment]
Don't know, hadn't given thought to 5.0. I couldn't figure out a way to mock the config without adding it to composer. I'll see about that.

I'll merge, but don't version it or anything, I'd like more time to try to test and improve it.

**Comment by omniphx** [comment]
Sounds like a good plan. I'll test it out some as well.

**Comment by rtconner** [comment]
This is looking good. I'm using it in my system now. Will let you know if any issues popup though.

**Comment by omniphx** [comment]
Awesome work. On a side note, I created a new branch (2.0) for Laravel 5 development.

There are some small differences in how configurations are managed, but the core stuff works fine.

**Comment by rtconner** [comment]
24 hours of use .. I feel good about it.
There are features I would like to add at some point. Like an "auto-authenticate" option or a "authenticate if token is expired" option. And I know you built in a retry if token is expired, so those might be more just small-optimizations.
