### ISSUE TITLE
PHPunit testing

### ISSUE THREAD

**Issue by CharbelJ** [omniphx/forrest#281]
Any idea on how to implement unit testing to pass the Forrest::auhenticate() method? or even mock Forrest::sobjects('Account', []):?

I want to be able to test the logic, but I'm always getting 'No token available' as PHPUnit does not expect to connect to Salesforce, but only to test the logic.

**Comment by AhmadWaleed** [comment]
Create new fake client for tests and define all the methods as stubs that you want to mock in test and then in tests swap real forrest client with your fake client imlementation.

```php
class FakeWebServerClient 
{
     public function auhenticate() {
        // return fake response
     }

    public function sobjects() {
        // return fake response
     }
}

Forrest::swap(new FakeWebServerClient);
```

in case you don't want to define all the stubs method on fake client then you can always mock client methods and replace with forrest service container

```php
$mock = \Mockery::mock(FakeWebServerClient::class)->shouldReceive('sobjects')->withAnyArgs()->andReturn([]);
$this->app->instance('forrest', $mock);
```
