### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by shaunthornburgh** [omniphx/forrest#282]
Hi,

I have created a connected app on Salesforce. Originally I set the callback uri to: 

https://login.salesforce.com/services/oauth2/token

However after reading through issues I found that this should be set to a local url for my development environment. I have updated this in my .env and in the connected app settings in salesforce.com. But I am still getting the following error:

<img width="1232" alt="Screenshot 2021-02-22 at 22 26 11" src="https://user-images.githubusercontent.com/3660684/108778719-b5f3e380-755d-11eb-98a2-942259bcce2c.png">

I am trying to authenticate with username and password and have add this to my .env:

`SF_AUTH_METHOD=UserPassword`

I have this in my web.php

```
Route::get('/authenticate', function()
{
    Forrest::authenticate();
    return Redirect::to('/');
});
```

I have cleared my cache, any suggestions on how I can get this resolved would be very much appreciated...

**Comment by omniphx** [comment]
Did you append a security token to the end of your password? That's required if you don't whitelist your IP address. Also, check you user in Salesforce and see if there are more details for the failed login attempt. Sometimes that can provide clues.

**Comment by shaunthornburgh** [comment]
Thank you @omniphx, the issue was in Salesforce, I changed 'permitted users' from 'Admin approved users are pre-authorized' to 'All users may self-authorize' and this fixed the issue for me.
