### ISSUE TITLE
File upload

### ISSUE THREAD

**Issue by asivaneswaran** [omniphx/forrest#283]
Hi,

I was wondering if it was possible to upload a Document using this package?
We tried using using the `Forrest::sobject('Document')` but we are not getting anywhere. Is it currently supported or do we have to make our implementation?

Thanks a lot,

**Comment by AhmadWaleed** [comment]
this link will help you understand about uploading documents and linking them with objects https://stackoverflow.com/questions/48635857/mass-upload-files-to-specific-contacts-salesforce/48668673#48668673

Here is the action class i am currently using to upload and attach documents with objects. if you're curious how this action is implemented, i have created a little orm package on top of forrest which easily lets interact with salesforce objects.
https://github.com/AhmadWaleed/soquel
```php
class UploadDocument
{
    protected UploadedFile $file;
    protected BaseObject $entity;

    public function __construct(UploadedFile $file, BaseObject $entity)
    {
        $this->file = $file;
        $this->entity = $entity;
    }

    public function execute()
    {
        $document = new ContentVersion;
        $document->Title = $this->file->getClientOriginalName();
        $document->PathOnClient = $this->file->getRealPath();
        $document->VersionData = base64_encode($this->file->getContent());
        $document = $document->save();

        $docLink = new ContentDocumentLink;
        $docLink->ContentDocumentId = $document->ContentDocumentId;
        $docLink->LinkedEntityId = $this->entity->Id;
        $docLink->ShareType = DocumentLinkShareType::INFERRED;
        $docLink->Visibility = DocumentLinkVisibility::ALL_USERS;
        $docLink->save();
    }
}
```
