### ISSUE TITLE
If you try to update a record using a composite resource, the HTTP will become GET instead of PATCH.

### ISSUE THREAD

**Issue by Yuki311** [omniphx/forrest#287]
In order to save the number of API calls, we are trying to update custom and standard objects using [composite resources](https://developer.salesforce.com/docs/atlas.ja-jp.228.0.api_rest.meta/api_rest/resources_composite_sobjects_collections_upsert.htm).

`            Forrest::composite('sobjects/UnsubscribeReason__c/id__c', 'patch', $body);
`

I tried to write the code as shown below, but I got the following error.
`GuzzleHttp\Exception\ClientException: Client error: GET https://d5g000002fkjreas.my.salesforce.com/services/data/v51.0/composite/sobjects/UnsubscribeReason__c/id__c resulted in a 405 Method Not Allowed response:
[{"errorCode":"METHOD_NOT_ALLOWED","message":"HTTP Method 'GET' not allowed. Allowed are PATCH"}]`

Inside the variable body, I wrote the following.

`                $body[] = [
                    'attributes' => [
                        'type' => 'UnsubscribeReason__c',
                    ],
                    'id__c' => $id,
                    'user__c' => $user_id,
                    'reason__c' => $reason,
                    'unsubscribe_date__c' => $unsubscribe_date,
                ];
`

I would appreciate it if you could tell me about this as I just can't figure it out.

I'm using a translator. I think my text is difficult to understand. I apologize for that. Please reply to me if you need any additional information.

**Comment by omniphx** [comment]
Hi @Yuki311 ,

Give this a try:
```php
$results = Forrest::composite('sobjects/UnsubscribeReason__c/id__c', [
    'method' => 'patch',
    'body'   => [
        'allOrNone' => false,
        'records' => $body
    ]
]);

dd($results);
```

**Comment by Yuki311** [comment]
Thank you for your answer.
