### ISSUE TITLE
REST API with access token

### ISSUE THREAD

**Issue by uxperience-hlaskov** [omniphx/forrest#288]
Hello, 

I am sorry, but I could find a way to authenticate with access token - like the described here

https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/quickstart_oauth.htm

thanks!

**Comment by omniphx** [comment]
With this library, `Forrest::authenticate();` handles that for you so you don't need worry about the low level details such as storing an access token

If you are just trying to learn how the Salesforce REST works, then you're probably better off using a vanilla solution

**Comment by uxperience-hlaskov** [comment]
Yes, that’s what I understand as well. The thing is: we don’t know which flow should I choose if I want to follow the instructions from https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/quickstart_oauth.htm - since there the ku option described is accesss token. That’s why I’m looking for help. 

Thanks!

**Comment by omniphx** [comment]
If you're trying to setup OAuth 2.0 (like the guide), then you'll want to choose the "WebServer" option. This will allow any user to login into your application with their credentials and access their Salesforce data

**Comment by uxperience-hlaskov** [comment]
I was given the instructions link to set-up API authentication, so that I can use my Laravel application to read/write from/to SalesForce. As far as I understand providing users to sign in is not an option. 

Rather the goal described in https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/quickstart_oauth.htm is to obtain an access token - which I should afterwards pass in the headers of my requested as bearer token in order to authenticate. Does that make any sense? And is it feasible with Forrest (and how)?

thank you very much for your time!

**Comment by omniphx** [comment]
Hi @uxperience-hlaskov, this library does store an encrypted access token on the application's behalf but there is no public method for accessing it.

If you need it for your requirements, I would recommend making an HTTP call to the `/services/oauth2/token` endpoint and include a username/password in the form fields.

Feel free to borrow any code from how it was implemented here: https://github.com/omniphx/forrest/blob/14783f2ebba4ce699a12a973cfdfb14387531d47/src/Omniphx/Forrest/Authentications/UserPassword.php#L41

hope that helps!

**Comment by uxperience-hlaskov** [comment]
Thank you, I believe it does. Will try it later today and let you know.
