### ISSUE TITLE
Creating instance by providing details

### ISSUE THREAD

**Issue by adam-devapp** [omniphx/forrest#290]
We wanted to create multiple instances of the Forrest connector to one or more sales force instances. When creating forest authenticate, can the following variables be passed in to the connector instead of using the configuration files.

        'consumer_key',
        'initial_access_token',
        'login_url',
        'callback_uri'

Alternatively what is the recommended approach for this?

**Comment by omniphx** [comment]
Hi @adam-devapp, did you take a look at this guide: https://github.com/omniphx/forrest#creating-multiple-instances-of-forrest

The one caveat is that you'll need to use the username/password flow. Not currently possible to handle OAuth with multiple instances

**Comment by omniphx** [comment]
And to answer the question about consumer keys and login urls. You can use the `setCredentials()` function:

```php
$forrest1->setCredentials(['username' => 'user@email.com.org1', 'password'=> '1234', 'consumerKey' => 'asdf']);
```

The property names will match the names inside the config file

**Comment by adam-devapp** [comment]
Sorry should have been clearer. I wanted to use the app credentials approach, rather than user password approach. I wanted to know if there was someway to override the information on the object before running it, so I can switch out the connection details.

**Comment by adam-devapp** [comment]
Thanks @omniphx for the information.

 Using this as a code example for the consumerkey and consumersecret method:

```
        $forrest1 = app()->make('forrest');

        $forrest1->setCredentials([
            'consumerKey' => 'xxx',
            'consumerSecret'=> 'xxxx',
            'loginUrl'=> 'https://xxx.lightning.force.com',  -- UAT. Will use salesforce main login URL in production
            'callbackURI' => 'https://xxxx/callback',
        ]);
        
        $forrest1 =  Forrest::query('select id, name from user');

```

When I got a local demo up and running using the config approach, I went to /authenticate and then it redirected back and I could use the Forrest queries for a day presumably until the token expired. Assuming I want to store the initial access token, refresh this token periodically and store in the DB.

Seemingly there is automatic code to handle the token storage and expiry, but the repo isn't persistent.

```
    'storage'        => [
        'type'          => 'session', // 'session' or 'cache' are the two options
        'path'          => 'forrest_', // unique storage path to avoid collisions
        'expire_in'     => 60, // number of minutes to expire cache/session
        'store_forever' => false, // never expire cache/sessionver expire cache/session
    ],
```
Is there an option for DB table to store the tokens which is more persistent than cache or session? i.e. Database. Or is there a way to override the token code by injecting the latest token with the credentials?

**Comment by adam-devapp** [comment]
I've been looking into the code around storage providers and LaravelSession is the default if you put a custom type. The config also mentions:
Set storage = object in the config file. This will store the token inside the object instance, but the documentation mentions this is only for the username and password method. It's not possible to specify a custom storage provider class in the configuration it would seem.

**Comment by omniphx** [comment]
@adam-devapp I think JWT would also work but I haven't tested it before

**Comment by omniphx** [comment]
And currently no way to initialize an instance with session token but that would nice. I know there is something similar built into [JSForce](https://jsforce.github.io/document/)

**Comment by adam-devapp** [comment]
Few questions:

Will using the SSL certificate (OAuthJWT) avoid the need for usernames and passwords?

I can't see a specific auth provider for:     'authentication' => 'OAuthJWT'

How is the private key specified in the config, as it doesn't have the key mentioned:
        'private_key' => file_get_contents('./../server.key'),
Also I can't see any passthrough key in the code to use the SSL.

What I'm trying to achieve is a server to server connection, that doesn't require each user to authenticate. The application will be authenticated to one or more instances, where the cache keys might be cleared now and then with updates... so it will need to remain persistent. 

What are your thoughts on the best way to achieve this. I agree with your comments that oAuth is more a user login rather than a server one.

**Comment by adam-devapp** [comment]
The forked version has an authentication provider for OAuthJWT, but the laravel version doesn't. So will force update to the latest and try again. Must be using an old version.
<img width="956" alt="Screen Shot 2021-09-11 at 10 58 31 am" src="https://user-images.githubusercontent.com/13082954/132931884-d146b73f-f294-4d36-8e89-afe095508e42.png">

**Comment by omniphx** [comment]
Yea, probably an older version. It is a pretty recent addition (last year or so).

**Will using the SSL certificate (OAuthJWT) avoid the need for usernames and passwords?**
You still need a username but no password. Since the SSL cert is used for essentially pre-authorizing users

**How is the private key specified in the config?**
If you have an older version it might not show up but you can take a look at the most up-to-date template: https://github.com/omniphx/forrest/blob/master/src/config/config.php

You got the right idea. JWT is definitely how I would go about for server-to-server setup. There's more setup at the beginning managing the certificates but you don't need to worry about storing passwords or having them expire/change.

**Comment by adam-devapp** [comment]
Thanks. Have done a new Laravel 8 install and new version has come down.

Have followed setup instructions. I'll make the SSL 999 days, so it won't expire any time soon.
Private key works into config. Finding the set credentials method isn't overriding:

```
        $forrest1 = app()->make('forrest');

        $forrest1->setCredentials([
            'consumerKey' => 'xxx',
            'loginUrl'=> 'https://login.salesforce.com',
            'callbackURI' => 'https://salesforce/callback',
        ]);

dd($forest);
```

Getting this error:
Client error: `POST https://xxxx--uat.my.salesforce.com/services/oauth2/token` resulted in a `400 Bad Request` response: {"error":"invalid_client_id","error_description":"client identifier invalid"}

The config says:
OAuthJWT requires a key, username, and private key (SF_CONSUMER_SECRET)

Which one is the client ID? Username have set as salesforce user. Do I also need to set SF_CONSUMER_SECRET as the private key?

**Comment by adam-devapp** [comment]
Seems the login URL is different for sandboxes:
https://githubmemory.com/repo/omniphx/forrest/issues/278

**Comment by adam-devapp** [comment]
Still getting this one though when running a query. The /authenticate now works.
```
Client error: `POST https://test.salesforce.com/services/oauth2/token` resulted in a `400 Bad Request` response: {"error":"invalid_client_id","error_description":"client identifier invalid"}
```

The consumerkey and secret are copied and pasted into the .env
The private key is selected and is readable to the class.
<img width="1046" alt="Screen Shot 2021-09-12 at 3 52 56 pm" src="https://user-images.githubusercontent.com/13082954/132974480-0613c3b9-c1a9-4603-bc11-058e256a1501.png">
<img width="950" alt="Screen Shot 2021-09-12 at 3 53 03 pm" src="https://user-images.githubusercontent.com/13082954/132974484-8f1e9016-bbb9-4ce9-a814-0d9480bbeea2.png">
<img width="1058" alt="Screen Shot 2021-09-12 at 3 53 12 pm" src="https://user-images.githubusercontent.com/13082954/132974485-4a5f21b2-036e-43c8-a97b-7125d75f52d3.png">
<img width="516" alt="Screen Shot 2021-09-12 at 3 53 55 pm" src="https://user-images.githubusercontent.com/13082954/132974488-53e81a30-bb1a-4f3f-864b-670583d06fb8.png">

**Comment by adam-devapp** [comment]
The salesforce login history shows: 


Failed: Missing Consumer Key Parameter
--

Yet the key is being provided in .env as SF_CONSUMER_KEY

**Comment by adam-devapp** [comment]
Finally worked. Recreated a new SSL and uploaded and now working.

**Comment by omniphx** [comment]
Thanks for documenting the solution! Glad you got it working
