### ISSUE TITLE
Help: How to access childSObject

### ISSUE THREAD

**Issue by shahvirag** [omniphx/forrest#293]
I am able to access child relationships

`Forrest::sobjects('Opportunity/describe')`

![Capture](https://user-images.githubusercontent.com/24240840/134676858-5b15de8c-2539-4410-aa9d-5b829f9a6caf.PNG)
I want to post consent.
How can i do that?

**Comment by omniphx** [comment]
You can access the child object with a new request: `Forrest::sobjects('Consent_and_Declaration__c/describe')`

**Comment by jqr91** [comment]
It's works but how can we get the related data without querying with sobject ?? 

For example:

`Forrest::sobjects("Account/Studies/describe")`

For me, return an error: Provided external ID field does not exist or is not accessible

**Comment by omniphx** [comment]
Are you using the correct API name for the Studies field? If it's a non-standard field it would probably look something like this: `Forrest::sobjects("Account/Studies/describe")`

Also, if you just looking for data. You would want to use `query()` instead of `sobjects()`
