### ISSUE TITLE
Help Needed: Null on Job Status response

### ISSUE THREAD

**Issue by shahvirag** [omniphx/forrest#295]
1) Get Job Detail
$job = Forrest::jobs('ingest/JOBID');

Get Job Detail properly.

2) Get Job Results
$result = Forrest::get('/services/data/v53.0/jobs/ingest/JOBID/successfulResults');

Getting Null every time calling this endpoint.

Ref: https://trailhead.salesforce.com/en/content/learn/modules/api_basics/api_basics_bulk

Thanks.

**Comment by roblesterjr04** [comment]
Why don't you try this:

```php
$job = Forrest::jobs('ingest/JOBID/successfulResults');
```

Might work maybe?

**Comment by shahvirag** [comment]
#297
