### ISSUE TITLE
No token available

### ISSUE THREAD

**Issue by sospcie** [omniphx/forrest#296]
Hi,

I am having an issue where I am not sure how to fix.

I am using Forrest in command mode. When larger data is returned, I am checking the returned data to see if the done key is 0 or 1, and if is 0 then I call Forrest with the nextRecordsUrl

That works for few steps but then suddenly it display No token available.

As an example, the total record count returned is 11226, and data returned by a chunks of 200.

Sometime on the 13th call some other time on 18th call (looks like random), I am getting the error.

Anyone have any clue why suddenly the token is nt available?

**Comment by omniphx** [comment]
Thanks for catching this @sospcie, looks like "minutes" > "seconds" happened after Laravel 5.8 was released.

I pushed up some changes today to make the comments in the config file accurately represent that number.
