### ISSUE TITLE
Where do I put the refresh_token? No refresh token stored in current session.

### ISSUE THREAD

**Issue by andrecuellar** [omniphx/forrest#301]
Hello, I already have the API configured, I am making queries using the library, however, it is completely necessary for me that salesforce does not ask for a username or password, nor does the user have to start a session or "authorize" the API.

I understand that this is what the refresh_token is for, am I correct?

This is because I have to do a daily synchronization of my web app with salesforce, and for this, I need to have the session always open and that the users of my application never have to accept anything, much less login to salesforce

To do this, I am using `Forrest::refresh();` before my line of `Forrest::query("MY QUERY");`

I get this error at the moment if I use `Forrest::refresh();`

`No refresh token stored in current session. Verify you have added refresh_token to your scope items on your connected app settings in Salesforce.`

but the problem is that I don't know if I'm doing it right or I don't know where to put the key of "refresh_token"

In my .env file, I already have the consumer_key, consumer_secret, callback_uri, login_url, username, and password. but I haven't put any refresh_token because I don't know where I should put it

These are my OAuth Policies in salesforce:

Permitted Users:	All users may self-authorize	
IP Relaxation:	Enforce IP restrictions
Refresh Token Policy:	Refresh token is valid until revoked
Single Logout:	Single Logout disabled	 	 
Application Permissions:	Perform requests at any time	 	 
 	                                Full access	 	 
 	                                Manage user data via Web browsers	 	 
 	                                Manage user data via APIs

where should I put the refresh_token key?

**Comment by omniphx** [comment]
Hey @andrecuellar,

When setting up your Connected App did you include the refresh_token in your scope access?

There's details about that here: https://github.com/omniphx/forrest#setting-up-a-connected-app

**Comment by andrecuellar** [comment]
> Hey @andrecuellar,
> 
> When setting up your Connected App did you include the refresh_token in your scope access?
> 
> There's details about that here: https://github.com/omniphx/forrest#setting-up-a-connected-app



No, because I have not found an option that allows me to add that key to the scope, on API (Enable OAuth Settings)

Or do I have to add it in OAuth Custom Scopes?
![image](https://user-images.githubusercontent.com/7474035/152425069-5381fff8-8686-4dc8-a289-61c994749089.png)

**Comment by omniphx** [comment]
It's a little hard to navigate, you want to make sure you click "Edit" under "Connected Apps"
![2022-02-03_15-50-45](https://user-images.githubusercontent.com/3722405/152426652-36322f91-6e27-459d-9f75-2adf33bdd1a9.png)

Then you should see a way to add "refresh_token" to your selected OAuth scopes
![2022-02-03_15-46-43](https://user-images.githubusercontent.com/3722405/152426714-4324a6ba-dea9-44a6-b024-f8f8e2e6259a.png)

**Comment by omniphx** [comment]
To answer your previous question, `refresh_token` will be stored automatically as long as it's included in the access scope

**Comment by andrecuellar** [comment]
> It's a little hard to navigate, you want to make sure you click "Edit" under "Connected Apps" ![2022-02-03_15-50-45](https://user-images.githubusercontent.com/3722405/152426652-36322f91-6e27-459d-9f75-2adf33bdd1a9.png)
> 
> Then you should see a way to add "refresh_token" to your selected OAuth scopes ![2022-02-03_15-46-43](https://user-images.githubusercontent.com/3722405/152426714-4324a6ba-dea9-44a6-b024-f8f8e2e6259a.png)

I already had that added since I created the connection, however I get that error.

Does that mean I don't need to add the key somewhere in salesforce?

Do I need yes or yes to do authentication? Or do I need to configure something in the library so that I can do the query without the user having to log in and accept the authorization?

**Comment by omniphx** [comment]
Sorry, was a little confused about what you were asking about earlier. If you're using WebServer or UserPassword auth flows you need to authenticate first. The authentication provides the refresh token.

From the other thread, sounds like you settled on JWT. That's probably the better authentication option for your use case since you want your users to be pre-authorized.
