### ISSUE TITLE
Error: "invalid_grant". "audicence is invalid"

### ISSUE THREAD

**Issue by andrecuellar** [omniphx/forrest#302]
Hello, I am trying to use this library to do synchronizations using Jobs, I have already created the .key and .crt with the command. I followed all the steps indicated in the readme, in salesforce, I already configured everything as indicated in the readme

```
openssl req -newkey rsa:2048 -nodes -keyout Area_Check.key -x509 -days 365 -o
ut Area_Check.crt
```

Currently, in `config/forrest.php` I have
`'authentication' => env('SF_AUTH_METHOD', 'OAuthJWT'),`
and
`'privateKey' => file_get_contents('Area_Check.key'),`

I don't know if this is correct, I have both files at the root of my project (at the same level as the .env, for example)

in my test code, i have this line of code
        Forrest::authenticate();
        $productQuery = Forrest::query("MYQUERY");

but I get this error
```
GuzzleHttp\Exception\ClientException
Client error: `POST https://lillyholdings--test.my.salesforce.com/services/oauth2/token` resulted in a `400 Bad Request` response: {"error":"invalid_grant","error_description":"audience is invalid"}
```

if I remove the auth line I get the following error:
```
Omniphx\Forrest\Exceptions\MissingTokenException
No token available
```

I'm missing something? I am following the steps in the readme

My SF_LOGIN_URL is `SF_LOGIN_URL=https://lillyholdings--test.my.salesforce.com`

If I edit that LOGIN_URL to https://test.salesforce.com I get this error
```
Client error: `POST https://test.salesforce.com/services/oauth2/token` resulted in a `400 Bad Request` response: {"error":"invalid_grant","error_description":"user hasn't approved this consumer"}
```

Note: I'm working with a salesforce sandbox

to avoid possible permission issues, I have changed to `Permitted Users All users may self-authorize` but the problem persits

**Comment by andrecuellar** [comment]
I have managed to solve the problem, the login URL has to be for sandbox, as it is in the readme, I thought I had to put the domain too
`SF_LOGIN_URL=https://test.salesforce.com`
It would be good if that was clarified in the readme

also, in salesforce, i have re-enabled 'Admin approved users are pre-authorized' but by giving all my users the permission, i need to find which one is being used (my problem)

then, I have seen that I must always keep the line Forrest::authenticate();
or is it possible to use the queries without using that line?

**Comment by omniphx** [comment]
The authentication needs to be called to initialize the application. After being called, the token will be stored in one of the storage options: `'session', 'cache', 'object'`

 You can read more about the session and cache storage options on Laravel's site. Object is just a plan in-memory object

You can check for an existing token using `Forrest::getToken()` if you need a way to see if it exists yet.
