### ISSUE TITLE
Can I Export Salesforce data for example some reports onto a page in my laravel vuejs application ?

### ISSUE THREAD

**Issue by abhinavarora14799** [omniphx/forrest#304]
I have successfully installed and authenticated on my application =, If anyone could help  how to display that would be really appreciated ?

**Comment by omniphx** [comment]
Hi @abhinavarora14799 , I would recommend checking out Laravel's documentation or Jeffrey Way's [Laracasts](https://laracasts.com/). Those resources would do a much better job answering your question about view states
