### ISSUE TITLE
Storing integer IDs in a Salesforce Custom Field with Number type

### ISSUE THREAD

**Issue by mbroadhead** [omniphx/forrest#312]
When you create a custom field of type **Number** in Salesforce, Forrest always returns a PHP float for that field. This means you can't reliably store IDs in a Number field because if you save "123", Forrest returns it as "123.0".
Example:
```
>>> $myId = 123
=> 123
>>> Forrest::sobjects("Opportunity/xyz123", ["method" => "patch", "body" => ["myId__c" => $myId]])
=> null
>>> $gotId = Forrest::sobjects("Opportunity/xyz123")['myId__c']
=> 123.0
>>> $gotId === $myId
=> false
```
While I think this is correct for Number custom fields that have a [scale](https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/customfield.htm#:~:text=or%20not%20(false).-,scale,-int) >= 1, I would argue that if the scale of a number custom field is set to 0, Forrest should return an int, not a float.

**Comment by omniphx** [comment]
Hi @mbroadhead, I believe this is just the format the Salesforce REST API returns all numbers regardless of the scale. Kind of strange, but no much I can do to fix this for you.
