### ISSUE TITLE
Argument #4 ($keyId) must be of type ?string,

### ISSUE THREAD

**Issue by adam-devapp** [omniphx/forrest#313]
TypeError: Firebase\JWT\JWT::encode(): Argument #4 ($keyId) must be of type ?string, array given, called in vendor/omniphx/forrest/src/Omniphx/Forrest/Authentications/OAuthJWT.php on line 22 in file vendor/firebase/php-jwt/src/JWT.php on line 17
<img width="1252" alt="connector" src="https://user-images.githubusercontent.com/13082954/162383055-fcb2cc14-36e8-4a02-97d1-40ec07f5d5d9.png">
8

The fourth argument is set in code (hard coded), so looks to be an error in the latest version. Was previously working fine.

**Comment by emaia** [comment]
I opened a PR about it #311

**Comment by adam-devapp** [comment]
Closing duplicate.

**Comment by omniphx** [comment]
@adam-devapp this fix should now be available in v2.14.1

**Comment by adam-devapp** [comment]
Working now in the new version.
