### ISSUE TITLE
Class "App\Http\Controllers\Forrest" not found - Question

### ISSUE THREAD

**Issue by Cruz-D** [omniphx/forrest#315]
hi all,
i follow the tutorial for try a simple query for testing the library, but laravel tell me forrest not found, put the class on the controller and equal to before, and im use a webserver login, I also made the connected app. **Where´s the problem?**
![Screenshot_1](https://user-images.githubusercontent.com/87978613/162703080-3fcf68ef-9d89-416d-8d92-0a602f103e4b.png)

**Comment by emaia** [comment]
Change `use App\Http\Controllers\Forrest` to `use Omniphx\Forrest\Providers\Laravel\Facades\Forrest;`.

**Comment by Cruz-D** [comment]
> use Omniphx\Forrest\Providers\Laravel\Facades\Forrest;

Its work, very thanks
