### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by cartwrightalex** [omniphx/forrest#318]
I am trying to authenticate within a laravel command with the following-

        $mySforceConnection = new Forrest();
        $mySforceConnection-> authenticate();
        $query = Forrest::query('SELECT Id, Username, LastName, FirstName, Name, CompanyName from Users);
        $responses = $mySforceConnection->queryAll($query);

Am receiving the following error when running the command-

 Call to undefined method Omniphx\Forrest\Providers\Laravel\Facades\Forrest::authenticate()

I am running Laravel 9.10.0

Thank you!

**Comment by omniphx** [comment]
Forrest is implemented with [Laravel Facades](https://laravel.com/docs/9.x/facades).  

Try this approach instead of initializing
```
Forrest::authenticate();
$query = "SELECT Id, Username, LastName, FirstName, Name, CompanyName from Users";

// Either of these query methods will work. `queryAll` returns deleted records
$responses = Forrest::query($query);
$responses = Forrest::queryAll($query);
```

**Comment by omniphx** [comment]
Also the approach above won't work if you are trying to use WebServer authentication due to needing a callback. Should be fine for JWT or UserPassword

**Comment by cartwrightalex** [comment]
This was very helpful, thanks for the quick response!
