### ISSUE TITLE
'No token available in current session'

### ISSUE THREAD

**Issue by obayesshelton** [omniphx/forrest#43]
Hey, got a slight problem I was wondering if you could help. I have also tested with different versions of forrest

**Using**

app/config/session

* 'driver' => 'file',

composer

* "laravel/framework"   : "4.2.*"
* "doctrine/dbal"           : "~2.3"
* "illuminate/support"    : "4.2.*,
* "guzzlehttp/guzzle"    : "~5.0"
* "omniphx/forrest"       : "1.1.0"

I keep getting the error

**'Omniphx\Forrest\Exceptions\MissingTokenException' with message 'No token available in current session'**

**Comment by omniphx** [comment]
Would you mind sharing your configuration file with your api keys removed?

**Comment by omniphx** [comment]
Also check to see if you have a token stored with this snippet (doesn't have to be a route, just a quick and dirty way to retrieve it):
```
Route::get('/token', function()
{
	$token = Session::get('token');
	echo"<pre>";
	print_r(Crypt::decrypt($token));
	echo"</pre>";
});
```

**Comment by rtconner** [comment]
What version of omniphx/forrest are you using?

**Comment by omniphx** [comment]
Are you still having trouble?

**Comment by obayesshelton** [comment]
No a friend of mine fixed it in another of yours issues. thanks :)
