### ISSUE TITLE
Put method not allowed

### ISSUE THREAD

**Issue by FatBoyXPC** [omniphx/forrest#59]
When I tried updating a record using the PUT HTTP method, Salesforce API complained and said that method wasn't allowed.

Allow' => array('HEAD,GET,PATCH,DELETE')

It appears like API v33.0 wants to use the PATCH method, instead. You can simply replace method => put with method => patch and everything is ok.

**Comment by omniphx** [comment]
Hi @FatBoyXPC,

There shouldn't be any issue with you using "PATCH" instead of "PUT". The PUT method is included in my codebase in case older versions of the API require it.

Can you provide an example of how you are trying to update the record? For instance, are you using `Forrest::sobject(['method' => 'patch'])` or `Forrest::patch(.....)`?

**Comment by FatBoyXPC** [comment]
Not sure if you saw the updated updated post, but I mentioned how simply
changing put to patch works just fine.

While I've got you, do you vu chance know why I can't update a contact name
via the api?

**Comment by omniphx** [comment]
Ah.. that makes sense. Didn't see the original post, so that's why I was confused.

I think the Contact record requires you to update "First name" and "Last name" separately. Not sure if that helps or not.

**Comment by FatBoyXPC** [comment]
I tried and wasn't able to, even with an underscore. I was only trying
first name by itself, though, maybe it wants both?

**Comment by FatBoyXPC** [comment]
I just played with all variations of "First Name". It ends up being FirstName and LastName are the field names. Case sensitivity does not matter, but I did that for clarity. Most field names can be retrieved by going to Setup > Customize > Object (Contacts, in my case) > Fields, and then looking at the Field Name column. Cool :) Things are looking great, dude!

**Comment by omniphx** [comment]
Oh nice! I didn't even think of that. I also use SoqlXplorer for API name: http://www.pocketsoap.com/osx/soqlx/

It's only for OSX, but I'm sure there's some similar clients apps for Windows. It's nothing fancy, but gets the job done.

**Comment by FatBoyXPC** [comment]
I'm a Linux fan boy :-(
