### ISSUE TITLE
Salesforce & TLS 1.0 phase-out

### ISSUE THREAD

**Issue by Harrisonbro** [omniphx/forrest#61]
I've just had an email from SalesForce saying:

> "Over the next 12 months, Salesforce is preparing to disable TLS 1.0 encryption in a phased approach to prevent it from being used to access the Salesforce service during inbound and outbound connections. [...] After Salesforce disables TLS 1.0 encryption, any channels connecting to Salesforce will need to use TLS 1.1 encryption or higher. Channels attempting to connect to Salesforce using encryption protocols lower than TLS 1.1 will NOT be able to connect to Salesforce. This includes browsers and any integrations to Salesforce APIs using unsupported encryption protocols."

Do you know whether this affects Forrest or does it use a different protocol to connect?

Thanks, Harrison

**Comment by omniphx** [comment]
Hi,

Won't affect this package. Thanks for checking.

-Matt

**Comment by Harrisonbro** [comment]
Great, thanks for letting me know!

**Comment by Harrisonbro** [comment]
@omniphx I've just had another look into the TLS usage for our SalesForce instance and found that Forrest is indeed accessing SalesForce with the TLS 1.0 protocol, meaning that it will break in July when SalesForce turns off TLS 1.0 access.

I've gone into SalesForce and downloaded our login history, filtering by TLS 1.0, and found rows like this (some column omitted for brevity):

| Login Time       | Login Type        | Status  | Client Version | API Type | API Version | Login URL            | TLS Protocol | TLS Cipher Suite |
| ---------------- | ----------------- | ------- | -------------- | -------- | ----------- | -------------------- | ------------ | ---------------- |
| 11/04/2017 12:42 | Remote Access 2.0 | Success | N/A            | N/A      | N/A         | login.salesforce.com | TLS 1.0      | AES256-SHA       |

Can you think of which parts of Forrest might be accessing via the TLS 1.0 protocol and how we can work to update it? I'm happy to work on it and submit a PR if you point me in the right direction.

Thanks,
Harrison
