### ISSUE TITLE
Config::get('forrest::authRedirect') not working

### ISSUE THREAD

**Issue by AharonFeinstein** [omniphx/forrest#62]
Hi,

Config::get('forrest::authRedirect'); 

did not work for me, I needed to change it to Config::get('forrest.authRedirect');

Also the expire_in setting doesnt work for me, it always sets it to 20 minutes.  

Lastly, is there an option to set the refresh token to never expire?

**Comment by omniphx** [comment]
Hi @AharonFeinstein, I'll try to take a look at this over the weekend. Just got back from vacation, so I've been a little busy lately.

-Matt

**Comment by omniphx** [comment]
Hi @AharonFeinstein, the config namespacing issue is fixed. Just upgrade to version 2.0.1.

Currently, this codebase doesn't provide a method for storing the tokens forever. However, it wouldn't be too hard to add this feature. Essentially, `Cache:put('key','value','expiration')` would becomes `Cache::forever('key', 'value');` if its specified in the config. I'll add a new issue to track progress.
