### ISSUE TITLE
Store tokens forever option

### ISSUE THREAD

**Issue by omniphx** [omniphx/forrest#64]
Currently, this codebase doesn't provide a method for storing the tokens forever. This was brought up in #63

Need to add a config option for storing token forever. Something like `'storeForever' => true`

Then `Cache:put('key','value','expiration');` would becomes `Cache::forever('key', 'value');` if its specified in the config file.

**Comment by rkeppner** [comment]
I got the code done for this, and created a PR in #110, but somebody else is going to have to help out with the PhpSpec tests. I've been banging my head against it for an hour, but I can't spend any more time to learn it right now. Sorry.
