### ISSUE TITLE
Pass RequestException to SalesforceException

### ISSUE THREAD

**Issue by mstephens** [omniphx/forrest#74]
When catching a "RequestException" in the Forrest client it'd be useful if the exception could be passed through to the "SalesforceException" (line 768-776).

For example it'd be useful to get the status code of the exception (for missing records etc.) when catching SalesforceException (at the moment you have to a regex search.. how 80's :P)

**Comment by omniphx** [comment]
Hi @mstephens,

Do you think you could elaborate a little on this? Such as how to reproduce this? 

One thing I could do is make the SalesforceException extend Guzzle's RequestException. Then you could get the status code with something like this:
```
        try {
            // something
        } catch (SalesforceException $e) {
            dd($e->getResponse()->getStatusCode());
        }
```

**Comment by mstephens** [comment]
@omniphx that sounds reasonable, at the moment I'm having to do the following:

```
catch(SalesforceException $e) {
    if(preg_match('/HTTP\/1\.1\s([\d]{3})\s/', $e->getMessage(), $matches)) {
        $this->setStatusCode($matches[1]);
    }
}
```

As you say, it'd be great if you could receive the code back directly, for example for when a lead cannot be found and it returns 404.

**Comment by omniphx** [comment]
Hi @mstephens,

I feel terrible for making you wait this long. Been meaning to wrap this up for a while.

I haven't created a new version yet, but the master branch will now allow you to call the following methods: `$e->getResponse()->getStatusCode()` or `$e->getRequest()->getMethod()`

Those are just examples. You can take a look at Guzzle's Request and Response classes for more getter methods.

**Comment by mstephens** [comment]
@omniphx no worries, works great, thank you.

**Comment by mstephens** [comment]
Hi @omniphx is there any chance you can pass the error from Salesforce to the Exception? There's no way of accessing it now. 

In "assignExceptions" at [this line](https://github.com/omniphx/forrest/blob/master/src/Omniphx/Forrest/Client.php#L773)

For example the Salesforce error 
`Client error response [url] https://cs86.salesforce.com/services/data/v36.0/sobjects/Lead/XXXX [status code] 400 [reason phrase] [{"message":"cannot reference converted lead","errorCode":"CANNOT_UPDATE_CONVERTED_LEAD","fields":[]}]"`

At the moment is replaced by:

`Salesforce response error`

Perhaps the code could be passed through too?

**Comment by omniphx** [comment]
Hi @mstephens,

The SalesforceException is extending Guzzle's exception class (http://docs.guzzlephp.org/en/latest/quickstart.html#exceptions). You should still have access to the information you are looking for, but you have to be more explicit. For example:
``` php
try {
    $this->request();
} catch (SalesforceException $e) {
    $url = $e->getRequest()->getUrl();
    $statusCode = $e->getResponse()->getStatus();
    $reason = $e->getResponse()->getReasonPhrase();
    dd($url, $statusCode, $reason);
}
```
