### ISSUE TITLE
laravel service provider breaks route caching

### ISSUE THREAD

**Issue by Olofguard** [omniphx/forrest#75]
The routes included in the ForrestServiceProvider contain closures which break route caching in laravel 5. 

I may have missed something but these routes dont appear to be used anywhere. 

My solution was to extend the service provider and overwrite the boot method.

```php
public function boot()
{
    $this->publishes([
        __DIR__.'/../../../../config/config.php' => config_path('forrest.php'),
    ]);
}
```

**Comment by omniphx** [comment]
Hi @Olofguard,

I might end up removing the routes entirely (i usually override them anyways in my own projects).

Thanks for reporting!

**Comment by Olofguard** [comment]
:+1:
