### ISSUE TITLE
Usage in a SaaS Application

### ISSUE THREAD

**Issue by mistryb** [omniphx/forrest#77]
How could I used this plugin in a SaaS mult-tenant application. Right now, credentials are required to be stored in a config file which is not unique to all users. Is there any way to retrieve these credentials from the DB instead, allowing each user to define their own SalesForce Credentials?

**Comment by omniphx** [comment]
Hi @mistryb,

The Web Server authentication (aka Oauth 2.0), would the allow the users of the multi-tenant application to log into any Salesforce org and avoid the risk of storing customer login credentials into a DB. The credentials in the config (such as the consumer key) would just be used to register your app with Salesforce.

Does that answer your question?

-Matt

**Comment by mistryb** [comment]
Yes. Thanks for the clarifications!
