### ISSUE TITLE
Undefined index: refresh_token

### ISSUE THREAD

**Issue by greggberry** [omniphx/forrest#81]
I get the following exception on callback, please note that there is no option to actually configure refresh tokens, in salesforce under manage my app the refresh token policy is set to "Immediately expire refresh token" there is no option to choose anything else..

` in WebServer.php line 129
at HandleExceptions->handleError('8', 'Undefined index: refresh_token', 'E:\Code\vzm\vendor\omniphx\forrest\src\Omniphx\Forrest\Authentications\WebServer.php', '129', array('code' => 'dasdfasdf', 'tokenURL' => 'https://test.salesforce.com/services/oauth2/token', 'response' => object(Response), 'jsonResponse' => array('access_token' => 'asdfasd', 'signature' => 'asdfasdf', 'scope' => 'full', 'id_token' => 'asdf', 'instance_url' => 'https://cs80.salesforce.com', 'id' => 'https://test.salesforce.com/id/asdfasdf', 'token_type' => 'Bearer', 'issued_at' => '1455798605702'))) in WebServer.php line 129`

**Comment by omniphx** [comment]
Hey @greggberry, not sure if you meant to close this or not but you bring up a very good point. If no refresh token is available an exception should be thrown instead of this messy stacktrace.

**Comment by omniphx** [comment]
Misunderstood the original issue, should be working fine now. Added a null check before trying to store the refresh token.

**Comment by greggberry** [comment]
awesome thanks for the fix, who can i contact if i have questions regarding this package, don't really want to open issues for questions?

**Comment by omniphx** [comment]
thanks for asking, but i don't mind at all if you post questions here! :smile:

**Comment by greggberry** [comment]
Thanks!
I'm currently trying to use your package as part of a cron to sync data from salesforce. Obviously i'll need to store the token in cache but that seems to expire pretty quickly.

What i've now done is call Forrest::refresh() every time the script executes. Is there a way to check if the token has expired before calling refresh() or alternatively set the cache lifetime to forever?

**Comment by omniphx** [comment]
Is it expiring because of the cache expiring or because the token expires? If the token expires, you should receive a TokenExpirationException.

**Comment by greggberry** [comment]
I get a MissingTokenException, so I’m assuming the cache has expired. I’ve
set the cache to expire very far into the future in config/forrest.php



I’m not entirely sure what to do, if the cache has expired and this is run
as a background process, how do I re-authenticate?



*From:* Matt Mitchener [mailto:notifications@github.com]
*Sent:* 23 February 2016 04:02 PM
*To:* omniphx/forrest <forrest@noreply.github.com>
*Cc:* greggberry <gregg@bigg.co.za>
*Subject:* Re: [forrest] Undefined index: refresh_token (#81)



Is it expiring because of the cache expiring or because the token expires?
If the token expires, you should receive a TokenExpirationException.

—
Reply to this email directly or view it on GitHub
<https://github.com/omniphx/forrest/issues/81#issuecomment-187710559>.
------------------------------

No virus found in this message.
Checked by AVG - www.avg.com
Version: 2016.0.7442 / Virus Database: 4533/11681 - Release Date: 02/22/16
