### ISSUE TITLE
All errors are wrapped to Salesforce Response Error

### ISSUE THREAD

**Issue by neha2012** [omniphx/forrest#86]
When I hit salesforce API I get proper salesforce error as follows with same arguments. But "forrest" keeps giving me "Salesforce Response Error"

[
  {
    "message": "Duplicate Username.<br>The username already exists in this or another Salesforce organization. Usernames must be unique across all Salesforce organizations. To resolve, use a different username (it doesn't need to match the user's email address). ",
    "errorCode": "DUPLICATE_USERNAME",
    "fields": [
      "Username"
    ]
  }
]

**Comment by omniphx** [comment]
Hi @neha2012,

I should probably provide more documentation about this package's error handling. I apologize for that.

The SalesforceException is now extending Guzzle's exception class: (http://docs.guzzlephp.org/en/latest/quickstart.html#exceptions). 

For example:
``` php
try {
    $this->request();
} catch (SalesforceException $e) {
    $url = $e->getRequest()->getUrl();
    $statusCode = $e->getResponse()->getStatus();
    $reason = $e->getResponse()->getReasonPhrase();
}
```

Issue #74 has more details about why i made these changes, if you are curious.

**Comment by genjerdotcom** [comment]
hi omniphx ,

great plugin.
can i get example project with lumen salesforce REST API?

**Comment by omniphx** [comment]
@genjerdotcom, Laravel changed it's implementation of dispatcher when it upgraded to 5.4. So the error you see is due to this package being a dependency of the Laravel framework.

I'd recommend upgrading Lumen to the most recent version but 5.4 should work
