### ISSUE TITLE
Programmatically choose authentication

### ISSUE THREAD

**Issue by tabirkeland** [omniphx/forrest#89]
First off, great package.

Working on an application where I want users to use WebServer authentication, but I would like to be able to have backend scheduled processes use UserPassword authentication such that I can aggregate expensive SOQL results.

Currently any way of doing this?

`Config::set('forrest.authentication', 'UserPassword');` ?

**Comment by omniphx** [comment]
Hi @tabirkeland,

Could of ways you could do this:
# Create a seperate service provider use it to initialize the UserPassword class with the alternative configs passed in as a dependency
# Just give you users access to a refresh token and use the WebServer flow. When run in the background, just refresh the token before use

Hope that helps!

**Comment by tabirkeland** [comment]
@omnipresent thanks!  That did help.  Going with route 1.
