### ISSUE TITLE
EventInterface not implemented in Lumen Service Provider

### ISSUE THREAD

**Issue by smithyco** [omniphx/forrest#90]
```
FatalThrowableError in UserPassword.php line 15:
Type error: Argument 2 passed to Omniphx\Forrest\Authentications\UserPassword::__construct() must implement interface Omniphx\Forrest\Interfaces\EventInterface, instance of Omniphx\Forrest\Providers\Laravel\LaravelCache given, called in /home/vagrant/Code/api2.gohubble.com/vendor/omniphx/forrest/src/Omniphx/Forrest/Providers/Lumen/ForrestServiceProvider.php on line 64
```
This happened after I updated from version 5.2.0 to the latest version.

**Comment by smithyco** [comment]
It looks like the order of arguments in the Lumen ForrestServiceProvider needs to be updated to match the order of arguments for the Auth Providers.

**Comment by omniphx** [comment]
Hi @smithyco, thanks for reporting this bug. Should be resolved now when using the `dev-master`. Should be released soon.
