### ISSUE TITLE
Sales force callback cors

### ISSUE THREAD

**Issue by joaopaulonobrega** [omniphx/forrest#96]
in my application is enabled using cors , my front end is in a domain and the back end is in another , is working properly if i don't use ajax, but when I try to log into salesforce using ajax , the following error in my callback appears :

`XMLHttpRequest cannot load https://my-url-sales/services/oauth2/authorize?respon…lesforce%2Fcallback&state=https://my-url-sales. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.`

anyone have any solution?

**Comment by omniphx** [comment]
The only way to prevent this is to whitelist a domain from with the Salesforce org itself. Go to Security Settings > CORS and add the front-end domain.

If you are building an app to be used by other salesforce orgs, you'll need to handle the authentication on the backend domain and then serve the frontend separately.

Let me know if that helps!

**Comment by omniphx** [comment]
Also check out [JSForce](https://jsforce.github.io/). This package is meant to primary interact with Salesforce through the backend. However, a frontend package might better suit your needs.

**Comment by joaopaulonobrega** [comment]
hi, thank you for your answer, i  looked  this option into salesforce before of the post, this option only accept  https and i work with http, i go try the other these  alternatives.

**Comment by joaopaulonobrega** [comment]
I found the JSForce very exposed , redirect after returning the call, did not work because it processes the request and then redirects , I'm still looking for a way , ideas ?

**Comment by omniphx** [comment]
Can you open chrome's developer toolkit > network and screenshot/copy+paste the request headers? Don't feel like I have much to go on here besides wildly guessing.

**Comment by joaopaulonobrega** [comment]
@omniphx, The best solution was to authenticate without ajax , and after Forrest :: rollback, redirect to my application SPA , in my case , the other requests functioned normally with ajax, only authenticate i have this problem because redirect of the salesforce not send headers with cors. thanks for the ideas.

**Comment by omniphx** [comment]
No worries, glad you figured it out!
