### ISSUE TITLE
ajax request does not work

### ISSUE THREAD

**Issue by jpnobrega** [omniphx/forrest#97]
was testing the plugin, very good, everything works perfectly using the browser, but with ajax, nothing worked, I do not know which headers or cookies send in the request, would have some example using ajax? grateful.

**Comment by tabirkeland** [comment]
@jpnobrega which auth method are you using?  WebServer or UserPassword ?  Depending on which you might need to re-auth when the user makes and AJAX request.  This is something that could even be incorporated into a middleware.

**Comment by joaopaulonobrega** [comment]
hi, iam using UserPassword, with cache, session not working with ajax and Userpassword, how i used with cash, is not possible refresh token, you have a solution @tabirkeland ?

**Comment by joaopaulonobrega** [comment]
iam not try with middleware yet

**Comment by tabirkeland** [comment]
This is the middleware I wrote to keep the API user authenticated:

`<?php

namespace App\Http\Middleware;

use App;
use Forrest;
use Closure;

class ValidateSalesforceToken
{
    /**
     * Handle an incoming request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Closure  $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        // Look for the salesforce api session tokens, make sure its not the console running
        if (!$request->session()->has('forrest_token') && !App::runningInConsole()) {
            // Authenticate
            Forrest::authenticate();
        }

        return $next($request);
    }
}`

You could modify to use `$request->isAjax()` test and perform logic if it is.

**Comment by joaopaulonobrega** [comment]
I took a break in the login step , I will leave to settle this detail cache or session more pro end , I test your middleware , tnks

**Comment by JohnGeigerWS** [comment]
Trying to figure out how to authenticate within a controller using WebServer not UserPassword.  Works great through the browser but I am trying to use it as part of an API call to my application that then pushes and pulls data from salesforce.   

Am I just doing it wrong?!?  Or is there some way to incorporate the authenticate and callback within a middleware or my controller?

Any insight would be greatly appreciated.

**Comment by tabirkeland** [comment]
@JohnGeigerWS, are you asking if you can combine the authenticate and callback in the same route?  Or just have them in a controller?

If you _just_ want to have the routes in a controller, that's easy enough.

app/Http/routes.php:
`Route::get('/callback', ['as' => 'salesforce-callback', 'uses' => 'HomeController@salesforceCallback']);
Route::get('/authenticate', ['as' => 'salesforce-authenticate', 'uses' => 'HomeController@salesforceAuthenticate']);`

in your controller:
`use Forrest;

class HomeController
{
	public function salesforceAuthenticate()
	{
		Forrest::authenticate();
	}

	public function salesforceCallback()
	{
		Forrest::callback();

	    return Redirect::to('/');	
	}
}`

Here is a good explanation of the Salesforce WebServer flow:
https://help.salesforce.com/apex/HTViewHelpDoc?id=remoteaccess_oauth_web_server_flow.htm&language=en

**Comment by JohnGeigerWS** [comment]
@tabirkeland , Thanks a million for this.  I ended up using your first example and got more good info out of your second as well.  Super helpful and I truly appreciate it!

**Comment by tabirkeland** [comment]
@JohnGeigerWS no worries!

@joaopaulonobrega still an issue?

**Comment by joaopaulonobrega** [comment]
@tabirkeland Hi, i m using your middleware , it is working perfectly with ajax. tnks.

**Comment by tabirkeland** [comment]
@omniphx issue can be closed.
